[docm] Fix instance code
xitu/graphql.github.io pull request #119
Opened 2023-06-15 02:40 UTC by webvs2

Closes #<issue number>

## Description

2023-06-15 06:17 UTC, jonirrings commented
I will check it later, thx

2023-06-16 00:55 UTC, webvs2 commented
There was an error when I ran the example yesterday, and the method of entry has changed after understanding it

2023-06-16 03:36 UTC, jonirrings commented
great, but `{schema:schema}` may be shorten as `{schema}`

2023-06-16 03:47 UTC, jonirrings requested changes
just a few to fix

2023-06-16 03:47 UTC, jonirrings commented on src/content/code/code.md
> +graphql({schema:schema, source:'{ hello }', rootValue:root}).then((response) => {
`schema:schema` -> `schema`

2023-06-16 03:47 UTC, jonirrings commented on src/content/graphql-js/Tutorial-GettingStarted.md
> +graphql({schema:schema, source:'{ hello }', rootValue:root}).then((response) => {
same as above

2023-06-16 04:59 UTC, webvs2 commented on src/content/code/code.md
> +graphql({schema:schema, source:'{ hello }', rootValue:root}).then((response) => {
Ok, I'll adjust

2023-06-16 06:50 UTC, jonirrings approved these changes
Great, thanks for your contribution.

2023-06-16 06:50 UTC, merged