最佳实践 - 关于 Graphs 的思考 #6
xitu/graphql.github.io pull request #33
Opened 2017-07-22 06:19 UTC by Tina92

@sqrthree 翻译完成

2017-07-31 13:41 UTC, linonetwo commented
@Tina92  可以把这张图片加上去哈，我之前 P 的 https://github.com/GraphQL-China/graphql-china.github.io/pull/22/commits/36dc31c0465335a4e93eab8fcb770c4adcfba8d1#diff-3b41b1a4f9a7fee9402dcf4ed0898242

2017-08-01 13:07 UTC, linonetwo requested changes
有一些用词和造句需要调优哈

2017-08-01 13:07 UTC, linonetwo commented on site/learn/BestPractice-ThinkingInGraphs.md
>  ![Business Logic Layer Diagram](/img/diagrams/business_layer.png)
这张图也翻译一下，可以用我之前翻译的  GraphQL-China/graphql-china.github.io@36dc31c#diff-3b41b1a4f9a7fee9402dcf4ed0898242

2017-08-01 13:07 UTC, linonetwo commented on site/learn/BestPractice-ThinkingInGraphs.md
> +## 一切皆是图形 [\*](https://en.wikipedia.org/wiki/Turtles_all_the_way_down)
图论不是图形，此处直接说图就好了，可以参考 https://github.com/GraphQL-China/graphql-china.github.io/pull/22/files

2017-08-01 13:07 UTC, linonetwo commented on site/learn/BestPractice-ThinkingInGraphs.md
> +> 使用 GraphQL，你可以将你所有的业务建模为图表
也不能说是图表，图表比较像是 chart，但此处是 graph theory 的 graph

2017-08-01 13:07 UTC, linonetwo commented on site/learn/BestPractice-ThinkingInGraphs.md
> +有时候，你会发现自己正在使用不能完全反映客户端消费数据的遗留数据源。在这种情况下，更倾向于构建一个描述客户端如何使用数据的 GraphQL 模式，而不是镜像遗留数据库模式。
schema 不翻译，参考 https://github.com/GraphQL-China/graphql-china.github.io/pull/22/files

2017-08-01 13:07 UTC, linonetwo commented on site/learn/BestPractice-ThinkingInGraphs.md
> +考虑下把你的 GraphQL 图作为一种给你的团队和用户的沟通的共同语言。为了建立一个好的模式，你必须检查你用来描述业务的日常语言。举个例子，让我们尝试用简单的英语描述一个电子邮件应用程序：
此处应该是用中文或自然语言

2017-08-01 13:07 UTC, linonetwo commented on site/learn/BestPractice-ThinkingInGraphs.md
> +命名是构建直观接口中一个困难但重要的部分，所以花时间仔细的考虑对于你的问题域和用户什么事有意义的。您的团队应该对这些业务领域的规则形成共同的理解和共识，因为您需要为 GraphQL 架构中的节点和关系选择直观，耐用的名称。试着去想象一些你想执行的查询：
我觉得「直观接口」可以改为「符合直觉的接口设计」

2017-08-04 09:30 UTC, linonetwo requested changes

2017-08-04 09:30 UTC, linonetwo commented on site/learn/BestPractice-ThinkingInGraphs.md
>  你应该在哪里定义真正的业务逻辑？你应该在哪里验证，检查用户权限？就是在专门的业务逻辑层里。你的业务逻辑层应作为执行业务域规则的唯一正确来源。
我品味了一下，觉得「执行……的正确来源」不是很符合中文语用，你觉得「唯一参考」怎么样？

2017-08-04 09:30 UTC, linonetwo commented on site/learn/BestPractice-ThinkingInGraphs.md
>  有时候，你会发现自己正在使用不能完全反映客户端消费数据的遗留数据源。在这种情况下，更倾向于构建一个描述客户端如何使用数据的 GraphQL 模式，而不是镜像遗留数据库模式。
我觉得你可以搜一下文档里的「模式」，都改成「schema」……

2017-08-04 09:30 UTC, linonetwo commented on site/learn/BestPractice-ThinkingInGraphs.md
>  图表是将很多真实世界现象变成模型的强大工具，因为它们和我们自然的心理模型和基本过程的口头描述很相似。通过 GraphQL，你会把自己的业务领域通过定义图表建模成一张图形；在你的图表里，你定义不同类型的节点以及它们之间是如何连接的。在客户端这边，这创建了一种类似于面向对象编程的模式：引用其他类型的类型。在服务器端，由于 GraphQL 定义了接口，你可以在任何后端自由的使用它（无论新旧！）。
这里图表应该是「图论」，「图论是将很多真实世界现象变成模型的强大工具」，后面的「图表」改成「图」就行了。中文对于「图论」的语用比较复杂。

2017-08-04 09:53 UTC, jonirrings requested changes
标头还是改回来，哈哈哈

2017-08-04 09:53 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +下一篇: /learn/serving-over-http/
这个，键部分……别翻译，属于标头文件，用于md工具生成的,，翻译了，md工具就蹦了。值部分，只翻译title,sidebartitle,category:joy:

2017-08-04 10:01 UTC, linhe0x0 requested changes

2017-08-04 10:01 UTC, sqrthree commented on site/learn/BestPractice-ThinkingInGraphs.md
> +在上图中，系统中的所有入口点（REST，GraphQL和RPC）都将使用相同的验证，授权和错误处理规则进行处理。
『REST，GraphQL和RPC』 =>『REST、GraphQL 和 RPC』注意标点符号和空格。

2017-08-04 10:01 UTC, sqrthree commented on site/learn/BestPractice-ThinkingInGraphs.md
> +不要试图一次就做一个模型来构建整个业务域。 而是一次只构建一个场景所需的部分图表。渐渐的拓展图表，为了寻找到构建的正确解决方案，你要更频繁地进行验证和获得反馈。
『渐渐的』=>『渐渐地』

2017-08-05 04:28 UTC, jonirrings requested changes

2017-08-05 04:28 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +-title: Thinking in Graphs
:joy:尴尬了，标头的title不用翻译成标题，但是Think in Graphs还是要翻译

2017-08-05 04:28 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +-category: Best Practices
顺便Best Practices 也翻译成最佳实践，:joy:

2017-08-09 04:20 UTC, linhe0x0 submitted a review, later dismissed

2017-08-09 04:21 UTC, sqrthree commented
@jonirrings Could u review this again?

2017-08-09 09:59 UTC, jonirrings requested changes
评论仅供参考，部分翻译需要按照wiki约定修正哈。@linonetwo 有空也来再过一遍

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +图表是将很多真实世界现象变成模型的强大工具，因为它们和我们自然的心理模型和基本过程的口头描述很相似。通过 GraphQL，你会把自己的业务领域通过定义图表建模成一张图形；在你的图表里，你定义不同类型的节点以及它们之间是如何连接的。在客户端这边，这创建了一种类似于面向对象编程的模式：引用其他类型的类型。在服务器端，由于 GraphQL 定义了接口，你可以在任何后端自由的使用它（无论新旧！）。
有劳将 图表 改作 图。这里指的是图论，而非图表

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +考虑下把你的 GraphQL 图作为一种给你的团队和用户的沟通的共同语言。为了建立一个好的模式，你必须检查你用来描述业务的日常语言。举个例子，让我们尝试用简单的中文描述一个电子邮件应用程序：
schema 协商的结果是保留不翻译。

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +考虑下把你的 GraphQL 图作为一种给你的团队和用户的沟通的共同语言。为了建立一个好的模式，你必须检查你用来描述业务的日常语言。举个例子，让我们尝试用简单的中文描述一个电子邮件应用程序：
plain english，其实翻译作“简单的文字”也不错哦

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +命名是构建符合直觉的接口中一个困难但重要的部分，所以花时间仔细的考虑对于你的问题域和用户什么事有意义的。您的团队应该对这些业务领域的规则形成共同的理解和共识，因为您需要为 GraphQL 架构中的节点和关系选择直观，耐用的名称。试着去想象一些你想执行的查询：
符合直觉的 -> 直观的，这样短点，哈哈 :joy:

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +命名是构建符合直觉的接口中一个困难但重要的部分，所以花时间仔细的考虑对于你的问题域和用户什么事有意义的。您的团队应该对这些业务领域的规则形成共同的理解和共识，因为您需要为 GraphQL 架构中的节点和关系选择直观，耐用的名称。试着去想象一些你想执行的查询：
仔细的 -> 仔细地

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +命名是构建符合直觉的接口中一个困难但重要的部分，所以花时间仔细的考虑对于你的问题域和用户什么事有意义的。您的团队应该对这些业务领域的规则形成共同的理解和共识，因为您需要为 GraphQL 架构中的节点和关系选择直观，耐用的名称。试着去想象一些你想执行的查询：
什么事有意义的 -> 什么事是意义的

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +命名是构建符合直觉的接口中一个困难但重要的部分，所以花时间仔细的考虑对于你的问题域和用户什么事有意义的。您的团队应该对这些业务领域的规则形成共同的理解和共识，因为您需要为 GraphQL 架构中的节点和关系选择直观，耐用的名称。试着去想象一些你想执行的查询：
GraphQL 架构 -> GraphQL schema
保留即可

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +![业务逻辑层图](https://github.com/GraphQL-China/graphql-china.github.io/blob/36dc31c0465335a4e93eab8fcb770c4adcfba8d1/site/img/diagrams/business_layer.png)
/img/diagrams/business_layer.png
这个还是改回来，哈哈

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +在上图中，系统中的所有入口点（REST、GraphQL和RPC）都将使用相同的验证，授权和错误处理规则进行处理。
相同的验证，授权和错误处理规则
->
相同的验证、授权和错误处理规则

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +### 使用遗留数据
这个legacy翻译作`旧有`如何？

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +> 希望构建一个描述客户端如何使用数据的 GraphQL schema，而不是镜像遗留数据库 schema。
同上，遗留 -> 现有，旧有

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +有时候，你会发现自己正在使用不能完全反映客户端消费数据的遗留数据源。在这种情况下，更倾向于构建一个描述客户端如何使用数据的 GraphQL 模式，而不是镜像遗留数据库模式。
同上，
遗留 -> 现有，旧有
GraphQL 模式 -> GraphQL schema 
数据库模式 -> 数据库 schema

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +构建一个表达“是什么”而不是“怎么做”的 GraphQL 模式。然后，您可以改进执行的具体细节，而不会破坏与旧客户端的接口。
GraphQL 模式 -> GraphQL schema

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +不要试图一次就做一个模型来构建整个业务域。 而是一次只构建一个场景所需的部分图表。渐渐地拓展图表，为了寻找到构建的正确解决方案，你要更频繁地进行验证和获得反馈。
图表 -> schema

2017-08-09 09:59 UTC, jonirrings commented on site/learn/BestPractice-ThinkingInGraphs.md
> +不要试图一次就做一个模型来构建整个业务域。 而是一次只构建一个场景所需的部分图表。渐渐地拓展图表，为了寻找到构建的正确解决方案，你要更频繁地进行验证和获得反馈。
为了寻找到构建的正确解决方案，你要更频繁地进行验证和获得反馈。
->
你要更频繁地进行验证和获得反馈，以便寻找到构建的正确解决方案。

2017-08-10 05:28 UTC, sqrthree commented
@Tina92 还有一些小问题需要你来看一下哈。

2017-08-10 06:26 UTC, linhe0x0 requested changes
37 行还有句英文呢。

2017-08-10 06:26 UTC, sqrthree commented on site/learn/BestPractice-ThinkingInGraphs.md
> +* 每封邮件都有发送人，接收日期，主题和正文
『发送人，接收日期，主题和正文』=> 『发送人、接收日期、主题和正文』

2017-08-10 06:39 UTC, jonirrings submitted a review, later dismissed

2017-08-10 06:40 UTC, Tina92 commented
@sqrthree 不好意思，忽略了

2017-08-10 06:41 UTC, linhe0x0 approved these changes

2017-08-10 06:53 UTC, merged