Learn-Queries.md
xitu/graphql.github.io pull request #37
Opened 2017-07-25 13:44 UTC by jonirrings

Signed-off-by: Jonir Rings <peterpuyi@live.cn>

2017-08-03 08:26 UTC, ydfzgyj requested changes
内容之前已校对过，格式上
1. 需要保留关键词的地方统一按照 中文翻译（英文关键词）的格式。
2. 链接之间增加空格
两处还需要再按新的格式规范修正一下

2017-08-03 09:19 UTC, jonirrings commented
已修改，有劳复查

2017-08-03 18:49 UTC, ydfzgyj requested changes

2017-08-03 18:49 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +sublinks: 字段（Fields）,参数(Arguments),别名(Aliases),片段(Fragments),变量(Variables),操作名称(Operation Name),指令(Directives),变更(Mutations),内联片段(Inline Fragments)
后边的括号全是英文的

2017-08-03 18:49 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +    # 查询可以有备注!
感叹号是英文的

2017-08-03 18:49 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +> 对了，还有一点 — 上述查询是*可交互的*。也就是你可以按你喜欢来改变查询，然后看看新的结果。尝试给查询中的 `hero` 对象添加一个` appearsIn` 字段，看看新的结果吧。
也是斜体改成粗体，这篇里的都是用的 * 啊……另一篇都是 _ 的

2017-08-03 18:49 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +参数可以是多种不同的类型。上面例子中，我们使用了一个枚举类型，其代表了一个有限选项集合（本例中为长度单位，即是 `METER` 或者 `FOOT` ）。GraphQL 自带一套默认类型，但是GraphQL 服务器可以声明一套自己的定制类型，只要能序列化成你的传输格式即可。
FOOT 和括号之间不加空格，第二个 GraphQL 之前加空格

2017-08-03 18:49 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +如果你眼睛够锐利，你可能已经发现，即便结果中的字段与查询中的字段能够匹配，但是因为他们并不包含参数，你就没法通过不同参数来查询相同字段。这便是为何你需要_别名_ — 这可以让你重命名结果中的字段为任意你想到的名字。
原来也有用下划线的……

2017-08-03 18:49 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +REST 中，任何请求都可能最后导致一些服务端副作用，但是约定上建议不要使用 `GET` 请求来修改数据。GraphQL 也是类似 — 技术上而言，任何查询都可以被实现为导致数据写入。然而，建一个约定来规范任何导致写入的操作都应该显示通过 变更（mutation）来发送。
看到一个错字，“显示”=>“显式”
另外变更前还是不要加空格吧

2017-08-03 18:49 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +## 内联片段(Inline Fragments）
左括号是英文

2017-08-03 18:49 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +### 元字段(Meta fields)
两个括号都是英文

2017-08-04 01:32 UTC, jonirrings commented on site/learn/Learn-Queries.md
> +如果你眼睛够锐利，你可能已经发现，即便结果中的字段与查询中的字段能够匹配，但是因为他们并不包含参数，你就没法通过不同参数来查询相同字段。这便是为何你需要_别名_ — 这可以让你重命名结果中的字段为任意你想到的名字。
我是按照原文换的啊……他用的md模版没细看，不知道有没区分_和单*。是翻译规范里面加了_和*转换规则么？

2017-08-04 01:36 UTC, jonirrings commented on site/learn/Learn-Queries.md
> +REST 中，任何请求都可能最后导致一些服务端副作用，但是约定上建议不要使用 `GET` 请求来修改数据。GraphQL 也是类似 — 技术上而言，任何查询都可以被实现为导致数据写入。然而，建一个约定来规范任何导致写入的操作都应该显示通过 变更（mutation）来发送。
这个空格是漏网之鱼……

2017-08-04 02:13 UTC, jonirrings commented on site/learn/Learn-Queries.md
> +参数可以是多种不同的类型。上面例子中，我们使用了一个枚举类型，其代表了一个有限选项集合（本例中为长度单位，即是 `METER` 或者 `FOOT` ）。GraphQL 自带一套默认类型，但是GraphQL 服务器可以声明一套自己的定制类型，只要能序列化成你的传输格式即可。
英文和标点符号之间也要空格？

2017-08-04 02:18 UTC, jonirrings commented
已修正，有劳再次审校。

2017-08-04 02:32 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +如果你眼睛够锐利，你可能已经发现，即便结果中的字段与查询中的字段能够匹配，但是因为他们并不包含参数，你就没法通过不同参数来查询相同字段。这便是为何你需要_别名_ — 这可以让你重命名结果中的字段为任意你想到的名字。
没加这个规则，只是吐槽原文也是乱用

2017-08-04 07:41 UTC, ydfzgyj requested changes

2017-08-04 07:41 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +sublinks: 字段（Fields）,参数Arguments）,别名（Aliases）,片段（Fragments）,变量（Variables）,操作名称（Operation Name）,指令（Directives）,变更（Mutations）,内联片段（Inline Fragments）
参数后边掉了一个括号

2017-08-04 07:41 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +    height（unit: FOOT)
这个括号为什么要换成中文的？

2017-08-04 07:41 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +  search（text: "an") {
你是不是批量替换的😂

2017-08-04 07:43 UTC, jonirrings commented on site/learn/Learn-Queries.md
> +  search（text: "an") {
咦，看来替换多了。

2017-08-04 08:04 UTC, jonirrings commented
已修正，有劳再次审校。喷血了:joy:，typo好多

2017-08-04 16:58 UTC, ydfzgyj requested changes

2017-08-04 16:58 UTC, ydfzgyj commented on site/learn/Learn-Queries.md
> +sublinks: 字段（Fields）,参数Arguments）,别名（Aliases）,片段（Fragments）,变量（Variables）,操作名称（Operation Name）,指令（Directives）,变更（Mutations）,内联片段（Inline Fragments）
“参数”后边那个括号……为啥没加

2017-08-05 04:31 UTC, jonirrings commented on site/learn/Learn-Queries.md
> +sublinks: 字段（Fields）,参数Arguments）,别名（Aliases）,片段（Fragments）,变量（Variables）,操作名称（Operation Name）,指令（Directives）,变更（Mutations）,内联片段（Inline Fragments）
:joy:，加上了

2017-08-05 04:34 UTC, jonirrings commented
@sqrthree 老大，这边有劳approve一下

2017-08-05 04:43 UTC, sqrthree commented on site/learn/Learn-Queries.md
> +在前一例子中，我们请求了我们主角的名字，返回了一个字符串类型（String），但是字段也能指代对象类型（Object）。这个时候，你可以对这个对象的字段进行 **次级选择（sub-selection）**。GraphQL 查询能够遍历相关对象及其字段，使得客户端可以一次请求查询大量相关数据，而不像传统 REST 架构中那样需要多次往返查询。
『次级选择』前面貌似多了个不必要的空格。

2017-08-05 05:04 UTC, jonirrings commented on site/learn/Learn-Queries.md
> +在前一例子中，我们请求了我们主角的名字，返回了一个字符串类型（String），但是字段也能指代对象类型（Object）。这个时候，你可以对这个对象的字段进行 **次级选择（sub-selection）**。GraphQL 查询能够遍历相关对象及其字段，使得客户端可以一次请求查询大量相关数据，而不像传统 REST 架构中那样需要多次往返查询。
好的，在IDE上有自动换行，没注意到。:joy:

2017-08-05 05:24 UTC, linhe0x0 approved these changes

2017-08-05 05:24 UTC, merged