Learn-Schema.md
xitu/graphql.github.io pull request #38
Opened 2017-07-25 13:45 UTC by jonirrings

Signed-off-by: Jonir Rings <peterpuyi@live.cn>

2017-08-03 08:31 UTC, ydfzgyj requested changes
内容之前已校对过，“需要保留关键词的地方统一按照 中文翻译（英文关键词）的格式。”以及其他一些细节还需要再按新的格式规范修正一下

2017-08-03 08:31 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +GraphQL 服务可以用任何语言编写，因为我们并不依赖于任何特定语言的句法句式（譬如 JavaScript ）来与 GraphQL schema 沟通，我们定义了自己的简单语言，称之为 “GraphQL schema 语言” —— 它和 GraphQL 的查询语言很相似，让我们能够和 GraphQL schema 之间可以无语言差异地沟通。
1. JavaScript 和右括号间不加空格
2. “GraphQL schema language”与其他译者商议保留原文，以避免出现不伦不类的“schema 语言”

2017-08-03 08:31 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +这表示_数组本身_可以为空，但是其不能有任何空值成员。用JSON举例如下：
JSON 前后加空格

2017-08-03 08:31 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +这表示数组本身不能为空，但是其可以包含空值成员:
冒号是英文符号

2017-08-03 08:31 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +你可以在查询指南的[内联片段](/learn/queries/#inline-fragments)章节了解更多相关信息。
链接前后加空格

2017-08-03 09:29 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +GraphQL 服务可以用任何语言编写，因为我们并不依赖于任何特定语言的句法句式（譬如 JavaScript ）来与 GraphQL schema 沟通，我们定义了自己的简单语言，称之为 “GraphQL schema 语言” —— 它和 GraphQL 的查询语言很相似，让我们能够和 GraphQL schema 之间可以无语言差异地沟通。
GraphQL schema language 和 GraphQL query language都保留不翻译么？

2017-08-03 09:30 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +这表示数组本身不能为空，但是其可以包含空值成员:
话说这些符号问题，你是用什么工具识别出来的？

2017-08-03 09:31 UTC, jonirrings commented
已修正，有劳再次审校

2017-08-03 13:27 UTC, ydfzgyj requested changes

2017-08-03 13:27 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +sublinks: 类型系统（Type System）,类型语言（Type Language）,对象类型和字段（Object Types and Fields）,参数（Arguments）,查询和变更类型（The Query and Mutation Types）,标量类型（Scalar Types）,枚举类型（Enumeration Types）,列表和非空（Lists and Non-Nul
Union Types 后边多了一个空格

2017-08-03 13:27 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +### 联合类型（Union Types ）
这里也多了一个空格

2017-08-03 13:27 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +目前为止，我们只讨论过将例如枚举和字符串等标量值作为参数传递给字段，但是你也能很容易地传递复杂对象。这在变更（mutation）中特别有用，因为有时候你需要传递一整个对象作为新建对象。在 GraphQL schema 语言中，输入对象看上去和常规对象一模一样，除了关键字是 `input` 而不是 `type`：
还有一处“schema 语言”

2017-08-03 13:27 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
>  一个 GraphQL schema 中的最基本的组件是对象类型，它就表示你可以从服务上获取到什么类型的对象，以及这个对象有什么字段。使用 GraphQL schema 语言，我们可以这样表示它：
还有一处“schema 语言”

2017-08-03 13:27 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +也称作_枚举（enum）_，枚举类型是一种特殊的标量，它限制在一个特殊的可选值集合内。这让你能够：
所有中文的斜体字都替换成加粗，出现了好几处，搜索下划线应该能全部找到

2017-08-03 13:28 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +GraphQL 服务可以用任何语言编写，因为我们并不依赖于任何特定语言的句法句式（譬如 JavaScript ）来与 GraphQL schema 沟通，我们定义了自己的简单语言，称之为 “GraphQL schema 语言” —— 它和 GraphQL 的查询语言很相似，让我们能够和 GraphQL schema 之间可以无语言差异地沟通。
query language 可以翻译，因为查询语言还是好理解的，schema 语言确实不知道是什么鬼东西

2017-08-03 13:29 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +这表示数组本身不能为空，但是其可以包含空值成员:
肉眼观察😂
因为原文是英文符号嘛，下边没有绿色的背景色就说明是没替换掉
你也可以在 PR 创建完还没提交的时候先自查一下

2017-08-04 01:40 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +也称作_枚举（enum）_，枚举类型是一种特殊的标量，它限制在一个特殊的可选值集合内。这让你能够：
看来我翻译规范看得不仔细:joy:

2017-08-04 01:43 UTC, jonirrings commented
已修正，有劳再次审校。

2017-08-04 07:38 UTC, ydfzgyj reviewed
还有最后一个空格，加油😂

2017-08-04 07:38 UTC, ydfzgyj commented on site/learn/Learn-Schema.md
> +目前为止，我们只讨论过将例如枚举和字符串等标量值作为参数传递给字段，但是你也能很容易地传递复杂对象。这在变更（mutation）中特别有用，因为有时候你需要传递一整个对象作为新建对象。在 GraphQL schema language中，输入对象看上去和常规对象一模一样，除了关键字是 `input` 而不是 `type`：
language 后边加空格

2017-08-04 08:05 UTC, jonirrings commented
已修正，有劳再次审校。:joy:

2017-08-04 16:59 UTC, ydfzgyj approved these changes
终于改完啦，棒棒哒

2017-08-05 04:31 UTC, jonirrings commented
@sqrthree 老大，这个也麻烦来approve一下

2017-08-05 04:51 UTC, linhe0x0 requested changes

2017-08-05 04:51 UTC, sqrthree commented on site/learn/Learn-Schema.md
> +- `Character` 是一个** GraphQL 对象类型**，表示其是一个拥有一些字段的类型。你的 schema 中的大多数类型都会是对象类型。
![image](https://user-images.githubusercontent.com/8622362/28992926-2df0be48-79dc-11e7-93da-8eb54935cc50.png)

2017-08-05 04:51 UTC, sqrthree commented on site/learn/Learn-Schema.md
> +###参数（Arguments）
![image](https://user-images.githubusercontent.com/8622362/28992937-84ddccd2-79dc-11e7-8ed1-99472fff4116.png)

2017-08-05 04:51 UTC, sqrthree commented on site/learn/Learn-Schema.md
> +对象类型，标量以及枚举是 GraphQL 中你唯一可以定义的类型种类。但是当你在 schema 的其他部分使用这些类型时，或者在你的查询变量声明处使用时，你可以给它们应用额外的**类型修饰符**来影响这些值的验证。我们先来看一个例子：
『对象类型，标量以及枚举』=>『对象类型、标量以及枚举』

2017-08-05 16:26 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +对象类型，标量以及枚举是 GraphQL 中你唯一可以定义的类型种类。但是当你在 schema 的其他部分使用这些类型时，或者在你的查询变量声明处使用时，你可以给它们应用额外的**类型修饰符**来影响这些值的验证。我们先来看一个例子：
已修正，有劳再次审查

2017-08-06 06:56 UTC, jonirrings commented on site/learn/Learn-Schema.md
> +- `Character` 是一个** GraphQL 对象类型**，表示其是一个拥有一些字段的类型。你的 schema 中的大多数类型都会是对象类型。
已修正，有劳再次审校

2017-08-09 04:27 UTC, linhe0x0 approved these changes

2017-08-09 04:27 UTC, merged