BestPractice-Authorization
xitu/graphql.github.io pull request #42
Opened 2017-07-26 08:21 UTC by ydfzgyj

2017-08-03 02:19 UTC, jonirrings submitted a review, later dismissed
已校对，无问题

2017-08-03 09:02 UTC, jonirrings submitted a review, later dismissed

2017-08-09 04:30 UTC, linhe0x0 requested changes

2017-08-09 04:30 UTC, sqrthree commented on site/learn/BestPractice-Authorization.md
> +*“只有作者才能看到他们自己的草稿”*
[斜体文字使用加粗样式代替](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E6%96%9C%E4%BD%93%E6%96%87%E5%AD%97%E4%BD%BF%E7%94%A8%E5%8A%A0%E7%B2%97%E6%A0%B7%E5%BC%8F%E4%BB%A3%E6%9B%BF)

2017-08-09 07:07 UTC, linhe0x0 approved these changes

2017-08-09 07:07 UTC, merged