Common Files
xitu/graphql.github.io pull request #46
Opened 2017-07-26 08:22 UTC by ydfzgyj

2017-07-26 10:06 UTC, linhe0x0 requested changes

2017-07-26 10:06 UTC, sqrthree commented on site/_core/Site.js
> +            {page && <a href={'https://github.com/GraphQL-China/graphql-china.github.io/edit/zh-cn/site/' + page.relPath} target="_blank" rel="noopener noreferrer">编辑本页 &#x270E;</a>}
这个编辑本页的链接需要调整一下啦

2017-07-26 16:33 UTC, ydfzgyj commented on site/_core/Site.js
> +            {page && <a href={'https://github.com/GraphQL-China/graphql-china.github.io/edit/zh-cn/site/' + page.relPath} target="_blank" rel="noopener noreferrer">编辑本页 &#x270E;</a>}
好的

2017-07-27 04:19 UTC, linhe0x0 approved these changes

2017-07-27 05:01 UTC, merged