完成 'Tutorial-ExpressGraphQL.md' 翻译
xitu/graphql.github.io pull request #48
Opened 2017-07-27 13:53 UTC by hikerpig

求校对

2017-07-28 18:10 UTC, ydfzgyj requested changes
一些标点上的小问题

2017-07-28 18:10 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ExpressGraphQL.md
>  var express = require('express');
有一句注释最好也翻译一下～

2017-07-28 18:10 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ExpressGraphQL.md
> +运行 GraphQL 最简单的方法是使用 [Express](https://expressjs.com)（一个 Node.js 上流行的 web 应用框架）。你需要安装两个依赖库:
最后一个冒号是英文标点

2017-07-28 18:10 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ExpressGraphQL.md
> +用以下命令启动该 GraphQL 服务器:
同冒号的问题

2017-07-28 18:10 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ExpressGraphQL.md
> +由于我们对 `graphqlHTTP` 设置 `graphiql: true`, 你可以使用 GraphiQL 工具来手动执行 GraphQL 查询。若使用浏览器浏览 `http://localhost:4000/graphql`，你会看到一个界面能让你输入查询语句。它看起来是这样的：
第一个逗号是英文标点

2017-07-28 18:10 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ExpressGraphQL.md
> +现在我们来改进 “hello world” 示例，把它从一个只能使用一个查询的简单的脚本变成一个 API 服务器。使用 `express` 模块来运行一个服务器，然后不再直接调用 `graphql` 函数进行查询，而是使用 `express-graphql` 库来构建 GraphQL API 服务器，响应以 '/graphql' 开头的 HTTP 请求。
1. 这里“以 '/graphql' 开头”不准确，只是针对“/graphql”这一个 endpoint，不包含以它开头的其它入口
2. endpoint 目前商议是统一翻译成“入口端点”

2017-08-02 05:33 UTC, hikerpig commented
更改完毕，等下一轮校对

2017-08-02 07:04 UTC, ydfzgyj requested changes

2017-08-02 07:04 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ExpressGraphQL.md
> +// 使用 GraphQL 模式语言创建一个 schema
这里还有一个 schema language

2017-08-02 07:04 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ExpressGraphQL.md
> +由于我们对 `graphqlHTTP` 设置 `graphiql: true`， 你可以使用 GraphiQL 工具来手动执行 GraphQL 查询。若使用浏览器浏览 `http://localhost:4000/graphql`，你会看到一个界面能让你输入查询语句。它看起来是这样的：
逗号后边多了一个空格

2017-08-02 07:04 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ExpressGraphQL.md
> +现在我们来改进 “hello world” 示例，把它从一个只能使用一个查询的简单的脚本变成一个 API 服务器。使用 `express` 模块来运行一个服务器，然后不再直接调用 `graphql` 函数进行查询，而是使用 `express-graphql` 库来构建 GraphQL API 服务器，响应入口端点为 '/graphql' 的 HTTP 请求。
最后的 '/graphql' 两边的引号与前边 “hello world” 保持统一为好

2017-08-02 12:47 UTC, ydfzgyj approved these changes

2017-08-04 03:42 UTC, jonirrings commented on site/graphql-js/Tutorial-ExpressGraphQL.md
> +运行 GraphQL 最简单的方法是使用 [Express](https://expressjs.com)（一个 Node.js 上流行的 web 应用框架）。你需要安装两个依赖库：
title，sidebarTitle和category也麻烦翻一下

2017-08-05 02:44 UTC, hikerpig commented on site/graphql-js/Tutorial-ExpressGraphQL.md
> +运行 GraphQL 最简单的方法是使用 [Express](https://expressjs.com)（一个 Node.js 上流行的 web 应用框架）。你需要安装两个依赖库：
噢漏漏翻，补上了

2017-08-05 04:14 UTC, jonirrings commented
那木有问题了

2017-08-05 04:14 UTC, jonirrings approved these changes
done

2017-08-05 04:15 UTC, merged