完成翻译 Tutorial-PassingArguments
xitu/graphql.github.io pull request #51
Opened 2017-07-29 09:40 UTC by Joursion

2017-08-02 07:34 UTC, ydfzgyj requested changes

2017-08-02 07:34 UTC, ydfzgyj commented on site/graphql-js/Tutorial-PassingArguments.md
> +// root 为每个 端点入口 API 提供一个解析器
中间多了一个空格

2017-08-02 07:34 UTC, ydfzgyj commented on site/graphql-js/Tutorial-PassingArguments.md
> +我们可能想要一个更通用的函数来实现投掷点数 `numDice` ，而不是硬性地设为 "3"，并且有一个参数 `numSide` 来表示骰子的面数，我们可以这样在 GraphQL schema language 实现：
这里的 numDice 应该不是投掷点数，而是投掷的骰子个数

2017-08-02 07:34 UTC, ydfzgyj commented on site/graphql-js/Tutorial-PassingArguments.md
> +当你调用这个 API 时，你需要按名称传入每个参数，对于上面的服务器代码，你可以通过发起这样的 GraphQL 查询，来投掷一个 6 面的，点数为 3 的骰子。
同上，这里应该是投掷 3 个六面的骰子

2017-08-02 07:34 UTC, ydfzgyj commented on site/graphql-js/Tutorial-PassingArguments.md
> +如果你使用 `node server.js` 运行这段代码，你可以浏览  http://localhost:4000/graphql 来尝试这个 API。
链接前边多了一个空格

2017-08-02 07:34 UTC, ydfzgyj commented on site/graphql-js/Tutorial-PassingArguments.md
> +使用 `$dice` 和 `$sides` 作为 GraphQL 中的变量，我们可以不用担心在客户端转义。
后半句表意不太清楚，可以改成“我们无需在客户端对它们进行转义”

2017-08-02 07:34 UTC, ydfzgyj commented on site/graphql-js/Tutorial-PassingArguments.md
> +通过基础类型和参数传递，你可以定义任意你在 REST API 中定义的内容。但 GraphQL 支持更强大的查询。如果你学习了 [定义你自己的对象类型](/graphql-js/object-types/)，你可以用单个 API 调用来代替多个 API 调用。
你可以定义任意你“能够”在 REST API 中定义的内容

2017-08-04 03:39 UTC, jonirrings commented on site/graphql-js/Tutorial-PassingArguments.md
> +就像 REST API 一样，在 GraphQL API 中，通常向入口端点传入参数，在 schema language 中定义参数，并自动进行类型检查。每一个参数必须有名字和数据类型。举个例子，在 [基础类型文档](/graphql-js/basic-types/) 中，我们定义了一个名为 `rollThreeDice` 的入口端点：
title和category部分也麻烦翻译下:+1:

2017-08-06 15:00 UTC, jonirrings commented
暂时没问题了，我先merge了

2017-08-06 15:01 UTC, jonirrings approved these changes

2017-08-06 15:01 UTC, merged

2017-08-07 13:20 UTC, ydfzgyj reviewed
还有一个小问题麻烦再修改一下

2017-08-07 13:20 UTC, ydfzgyj commented on site/graphql-js/Tutorial-PassingArguments.md
> +通过基础类型和参数传递，你可以定义任意你"能够"在 REST API 中定义的内容。但 GraphQL 支持更强大的查询。如果你学习了 [定义你自己的对象类型](/graphql-js/object-types/)，你可以用单个 API 调用来代替多个 API 调用。
“能够”两边的引号不需要的……我加引号的目的是表示这两个字漏了需要补上……我下次换成用加粗好了……虽然已经合并了，麻烦再修改一下

2017-08-07 13:26 UTC, jonirrings commented on site/graphql-js/Tutorial-PassingArguments.md
> +通过基础类型和参数传递，你可以定义任意你"能够"在 REST API 中定义的内容。但 GraphQL 支持更强大的查询。如果你学习了 [定义你自己的对象类型](/graphql-js/object-types/)，你可以用单个 API 调用来代替多个 API 调用。
:joy:有劳修改了，再PR一下

2017-08-08 01:24 UTC, Joursion commented on site/graphql-js/Tutorial-PassingArguments.md
> +通过基础类型和参数传递，你可以定义任意你"能够"在 REST API 中定义的内容。但 GraphQL 支持更强大的查询。如果你学习了 [定义你自己的对象类型](/graphql-js/object-types/)，你可以用单个 API 调用来代替多个 API 调用。
我是要重新提交一个PR 吗？

2017-08-08 01:57 UTC, jonirrings commented on site/graphql-js/Tutorial-PassingArguments.md
> +通过基础类型和参数传递，你可以定义任意你"能够"在 REST API 中定义的内容。但 GraphQL 支持更强大的查询。如果你学习了 [定义你自己的对象类型](/graphql-js/object-types/)，你可以用单个 API 调用来代替多个 API 调用。
嗯，直接新发pr吧，revert会导致一堆PR失效，比较麻烦。或者@sqrthree 看看怎么弄

2017-08-08 03:07 UTC, sqrthree commented on site/graphql-js/Tutorial-PassingArguments.md
> +通过基础类型和参数传递，你可以定义任意你"能够"在 REST API 中定义的内容。但 GraphQL 支持更强大的查询。如果你学习了 [定义你自己的对象类型](/graphql-js/object-types/)，你可以用单个 API 调用来代替多个 API 调用。
直接提交新 PR 即可。