API 参考-错误信息
xitu/graphql.github.io pull request #52
Opened 2017-07-29 15:05 UTC by XatMassacrE

原 Issues 地址：[#13](https://github.com/xitu/graphql.github.io/issues/13)

2017-08-02 07:39 UTC, ydfzgyj requested changes

2017-08-02 07:39 UTC, ydfzgyj commented on site/graphql-js/APIReference-Errors.md
> +`graphql/error` 模块负责创建和格式化 GraphQL 的错误信息。你可以直接从 `graphql/error`模块导入，也可以从 `graphql` 这个根模块导入。举例来说就是这样：
第二个 `graphql/error` 后边需要加一个空格

2017-08-02 07:39 UTC, ydfzgyj commented on site/graphql-js/APIReference-Errors.md
> +      根据响应格式的规则描述格式化一条错误信息。
根据响应格式的规则描述“来”格式化一条错误信息。

2017-08-02 07:39 UTC, ydfzgyj commented on site/graphql-js/APIReference-Errors.md
> +GraphQLError 表示 GraphQL 产生的错误信息。它包含一些用于调试的信息，比如 query 语句中错误发生的位置。最常见的错误信息就是下面的的 `locatedError` 。
query 可以直接翻译成“查询”

2017-08-02 07:39 UTC, ydfzgyj commented on site/graphql-js/APIReference-Errors.md
> +给定一个 GraphQLError，根据 GraphQL 说明中的响应格式和错误分类的规则描述格式化错误信息。
Specification 翻译成“规范”

2017-08-02 17:51 UTC, XatMassacrE commented
@ydfzgyj 感谢校对

2017-08-02 17:51 UTC, XatMassacrE commented
@sqrthree 已按照校对者的意见修改完毕。

2017-08-03 05:56 UTC, ydfzgyj requested changes

2017-08-03 05:56 UTC, ydfzgyj commented on site/graphql-js/APIReference-Errors.md
> +GraphQLError 表示 GraphQL 产生的错误信息。它包含一些用于调试的信息，比如查询语句中错误发生的位置。最常见的错误信息就是下面的的 `locatedError` 。
`locatedError` 和句号之间无需加空格

2017-08-03 05:56 UTC, ydfzgyj commented on site/graphql-js/APIReference-Errors.md
> +给定一个 GraphQLError，根据 GraphQL 规范中的响应格式和错误分类的规则描述格式化错误信息。
这里也有一个“……的规则描述‘来’格式化错误信息”，加上副词以免混淆“描述”的含义，因为上边出现了一次，我上次 review 的时候这里没有提，麻烦再修改一下

2017-08-04 10:43 UTC, XatMassacrE commented
@ydfzgyj 感谢校对

2017-08-04 10:44 UTC, XatMassacrE commented
@sqrthree 已按照校对者的意见修改完毕。

2017-08-04 17:00 UTC, ydfzgyj approved these changes

2017-08-09 15:48 UTC, linhe0x0 approved these changes

2017-08-09 15:49 UTC, merged