Tutorial - 起步
xitu/graphql.github.io pull request #53
Opened 2017-07-31 13:20 UTC by Tina92

@sqrthree 翻译完成 #25

2017-08-01 02:20 UTC, Joursion reviewed
初次校对。

2017-08-01 02:20 UTC, Joursion commented on site/graphql-js/Tutorial-GettingStarted.md
> +我们需要一个定义“Query”类型的图表来处理 GraphQL 查询。我们还需要一个 API 根节点，为每个 API 端点提供一个名为“resolver”的函数。对于只要返回“Hello world！”的 API，我们可以将此代码放在名为 `server.js` 的文件中：
`Query`   应该和原文保持一致吧， “Hello world” 前后的空格

2017-08-01 02:20 UTC, Joursion commented on site/graphql-js/Tutorial-GettingStarted.md
> +// 使用 GraphQL 图表语言构建一个图
schema 为 不需要翻译的英文关键词 ， 可以参考 wiki 里面的翻译术语表

2017-08-01 02:20 UTC, Joursion commented on site/graphql-js/Tutorial-GettingStarted.md
> +// 根节点为每个 API 端点提供一个 resolver 函数endpoint
endpoint 暂时翻译为 入口端点 ，详见 wiki

2017-08-02 07:20 UTC, ydfzgyj requested changes

2017-08-02 07:20 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GettingStarted.md
> +即使这些示例大部分在以前版本的 Node 中也能正常运行，你也应该至少在开始学习之前安装了 v6 版本以上的 Node 环境 。在本篇指南中，我们不会使用任何需要转换的语言特性，但是我们会使用 ES6 的部分新特性，比如 [Promises](http://www.html5rocks.com/en/tutorials/es6/promises/)，[classes](http://javasc
1. “v6 版本以上” => “v6 以上版本”
 2. Node 环境和句号中间不加空格

2017-08-02 07:20 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GettingStarted.md
> +我们需要一个定义“Query”类型的图表来处理 GraphQL 查询。我们还需要一个 API 根节点，为每个 API 端点提供一个名为“resolver”的函数。对于只要返回“Hello world！”的 API，我们可以将此代码放在名为 `server.js` 的文件中：
1. “resolver” 前后的空格
2. 对于“只”返回……

2017-08-02 07:20 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GettingStarted.md
> +// 运行 GraphQL query '{ hello }’ ，打印响应
1. 两个引号保持统一
2. 这里 print 翻译成“输出”应该更合适

2017-08-02 07:20 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GettingStarted.md
> +在实际应用中，你不会在命令行工具里执行 GraphQL，而是可能会想从一个 API 服务器 运行 GraphQL 查询。如何在 HTTP API 服务器运行 GraphQL，请查看[运行 GraphQL 服务器](/graphql-js/running-an-express-graphql-server/)章节。
1. 把 rather than 后边的语句提前的话，应当把 probably 这个词一并提前
2. “服务器 运行”应当去掉中间的空格
3. 链接“运行 GraphQL 服务器”的前后加上空格

2017-08-02 12:58 UTC, ydfzgyj requested changes

2017-08-02 12:58 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GettingStarted.md
> +// 使用 GraphQL 图表语言构建一个 schema
此处的 Schema Language 也保留原文即可

2017-08-02 12:58 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GettingStarted.md
> +// 运行 GraphQL query ’{ hello }’ ，输出响应
两个引号都是单引号的右引号，请换成一左一右

2017-08-02 12:58 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GettingStarted.md
> +在实际应用中，你可能不会在命令行工具里执行 GraphQL，而是会想从一个 API 服务器运行 GraphQL 查询。如何在 HTTP API 服务器运行 GraphQL，请查看[运行 GraphQL 服务器](/graphql-js/running-an-express-graphql-server/)章节。
参照翻译规范， `[运行 GraphQL 服务器](/graphql-js/running-an-express-graphql-server/)` 作为链接，前后应当加上空格

2017-08-03 05:08 UTC, ydfzgyj submitted a review, later dismissed

2017-08-03 06:08 UTC, jonirrings commented on site/graphql-js/Tutorial-GettingStarted.md
> +我们需要一个定义 `Query` 类型的图表来处理 GraphQL 查询。我们还需要一个 API 根节点，为每个 API 端点提供一个名为“resolver”的函数。对于只返回“Hello world！”的 API，我们可以将此代码放在名为 `server.js` 的文件中：
这个“图表”应该保留为schema吧？

2017-08-04 03:44 UTC, jonirrings commented on site/graphql-js/Tutorial-GettingStarted.md
> +## 学前准备
title，sidebarTitle和category也麻烦翻一下

2017-08-04 15:33 UTC, Tina92 commented on site/graphql-js/Tutorial-GettingStarted.md
> +## 学前准备
这个不用翻译了吧？？

2017-08-04 17:01 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GettingStarted.md
> +## 学前准备
@jonirrings 最好我们统一翻译一下，以免菜单出现错乱

2017-08-05 04:32 UTC, jonirrings commented on site/graphql-js/Tutorial-GettingStarted.md
> +## 学前准备
要翻译的，不过需要统一一下。开个issue吧。

2017-08-10 03:41 UTC, jonirrings requested changes

2017-08-10 03:41 UTC, jonirrings commented on site/graphql-js/Tutorial-GettingStarted.md
> +category: GraphQL.js 指南
Tutorial统一成 教程吧，guide翻译成 指南

2017-08-10 05:30 UTC, sqrthree commented
@Tina92 还有一些小问题需要麻烦你来看一下哈

2017-08-10 06:28 UTC, linhe0x0 requested changes

2017-08-10 06:28 UTC, sqrthree commented on site/graphql-js/Tutorial-GettingStarted.md
> +即使这些示例大部分在以前版本的 Node 中也能正常运行，你也应该至少在开始学习之前安装了 v6 以上版本的 Node 环境。在本篇指南中，我们不会使用任何需要转换的语言特性，但是我们会使用 ES6 的部分新特性，比如 [Promises](http://www.html5rocks.com/en/tutorials/es6/promises/)，[classes](http://javascr
『 Promises，classes 和 fat arrow functions。』=>『 Promises、classes 和 fat arrow functions。』

2017-08-10 06:37 UTC, jonirrings submitted a review, later dismissed

2017-08-10 07:30 UTC, linhe0x0 approved these changes

2017-08-10 07:34 UTC, merged