Learn-Introspection
xitu/graphql.github.io pull request #54
Opened 2017-07-31 13:30 UTC by linonetwo

求校对啦~

2017-08-03 19:02 UTC, ydfzgyj requested changes

2017-08-03 19:02 UTC, ydfzgyj commented on site/learn/Learn-Introspection.md
> +因此我们可以通过自省系统接触到类型系统的文档，并做出文档浏览器，或是丰富的 IDE 体验。
“丰富的 IDE 体验”和“做出文档浏览器”好像没有并列关系，在前边加上一个“提供”如何？

2017-08-03 19:02 UTC, ydfzgyj commented on site/learn/Learn-Introspection.md
> +如果我们设计了类型系统，我们自然知道哪些类型是可用的。但如果类型系统不是我们设计的，我们也可以问 GraphQL，通过查询 `__schema` 字段，一个查询的根类型总是有这个字段。现在来试试，查询一下有哪些可用的类型。
“我们也可以问 GraphQL”这句，断句有一点奇怪

2017-08-04 01:38 UTC, jonirrings commented
@linonetwo @ydfzgyj 话说，introspection翻译作 内省 还是 自省？比较好。Java里面是内省

2017-08-04 07:44 UTC, ydfzgyj commented
> 话说，introspection翻译作 内省 还是 自省？比较好。Java里面是内省

唔……那就内省吧，我觉得没有区别……定下来的话，就在术语表里加一下

2017-08-04 09:34 UTC, linonetwo commented on site/learn/Learn-Introspection.md
> +因此我们可以通过自省系统接触到类型系统的文档，并做出文档浏览器，或是丰富的 IDE 体验。
哈哈 初中病句修改题

2017-08-04 09:47 UTC, jonirrings commented
@ydfzgyj 已经添加到wiki了。大致没问题了吧？那我也approve了

2017-08-04 09:47 UTC, jonirrings approved these changes
done

2017-08-04 09:48 UTC, merged