翻译完成请校对
xitu/graphql.github.io pull request #55
Opened 2017-08-01 06:48 UTC by whisperfairy

翻译完成请校对

2017-08-02 13:14 UTC, ydfzgyj requested changes

2017-08-02 13:14 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +在验证环节之后，GraphQL服务端在处理数据之后，会根据GraphQL query的请求内容生成对应结构的结果，一般情况下会以JSON形式返回。
请参照 [翻译术语表](https://github.com/xitu/graphql.github.io/wiki/%E7%BF%BB%E8%AF%91%E6%9C%AF%E8%AF%AD%E8%A1%A8) 和 [翻译规范指南](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97) 先对文章做一遍自查吧

2017-08-09 15:59 UTC, sqrthree commented
@whisperfairy 文中有很多问题，辛苦你参照 [翻译术语表](https://github.com/xitu/graphql.github.io/wiki/%E7%BF%BB%E8%AF%91%E6%9C%AF%E8%AF%AD%E8%A1%A8) 和 [翻译规范指南](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97) 调整一下哈。

2017-08-14 15:37 UTC, whisperfairy commented
修改了一遍，抱歉耽误了大家的时间

2017-08-15 04:14 UTC, linhe0x0 requested changes

2017-08-15 04:14 UTC, linhe0x0 commented on site/learn/Learn-Execution.md
> +这个例子使用了 JavaScript 语言，但 GraphQL 服务端应用可以被 [多种语言实现](https://github.com/whisperfairy/graphql-china.github.io/blob/zh-cn/code) .无论哪种语言，解析器函数都接受3个参数
『多种语言实现』后面的标点请用全角。

2017-08-15 04:14 UTC, linhe0x0 commented on site/learn/Learn-Execution.md
> +这个例子使用了 JavaScript 语言，但 GraphQL 服务端应用可以被 [多种语言实现](https://github.com/whisperfairy/graphql-china.github.io/blob/zh-cn/code) .无论哪种语言，解析器函数都接受3个参数
数字前后需要加一个空格。

2017-08-15 04:14 UTC, linhe0x0 commented on site/learn/Learn-Execution.md
> +- `context` 会被提供了所有解析器，并且持有重要的上下文信息比如当前登入的用户或者数据库访问对象
75, 76 这两行没有结束标点。

2017-08-15 04:14 UTC, linhe0x0 commented on site/learn/Learn-Execution.md
> +在这个例子中，对 name 字段的处理非常的清晰， name 字段对应的解析器函数调用了在上层回调函数生成的 `new Human` 对象在这个案例中，我们设计Human对象会拥有一个 `name` 属性可以让我们从 obj 对象中直接读取。
『Human』前后缺少空格。

2017-08-15 04:14 UTC, sqrthree commented on site/learn/Learn-Execution.md
> +当 `name` 字段被处理后，`appearsIn` 和 `starships` 字段可以被同步执行， `appearsIn` 字段
『`appearsIn` 字段』怎么了？之后呢？

2017-08-15 04:14 UTC, sqrthree commented on site/learn/Learn-Execution.md
> +这是标量强制的一个例子。类型系统知道预期的内容，并将将解析器函数返回的值转换为维护 API 合同的内容。在这种情况下，可能在我们的服务器上定义了一个枚举类型，但解析器在内部使用 4,5 和 6 的整数类型，但在 GraphQL 类型系统中将它们表示为枚举值，如果类型不匹配将返回 null，并提示错误。
『4,5』=>『4、5』

2017-08-15 04:14 UTC, sqrthree commented on site/learn/Learn-Execution.md
> +GraphQL 将在同步执行这些 Promise，当返回一个对象列表，它将继续同步加载每个这些对象的 `name` 字段。
这一句话不太通顺，建议调整一下。@ydfzgyj 你觉得呢？

2017-08-15 04:32 UTC, whisperfairy commented
收到，马上修改

2017-08-15 05:54 UTC, linhe0x0 submitted a review, later dismissed

2017-08-15 06:59 UTC, ydfzgyj requested changes
翻译不是自己的博客，还是要遵循原文的，这篇有些地方的译文感觉跟原文已经没有关系了，自我发挥的成分太大
然后还有几句明显看得出机翻的痕迹，整体风格明显不统一，希望不要因为时间不够就机翻赶进度
问题比较多，请好好再过一遍

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +```
graphql 不能去掉，否则网站不能解析，下同

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +在验证环节之后，GraphQL 服务端在处理数据之后，会根据 GraphQL 查询的请求内容生成对应结构的结果，一般情况下会以JSON形式返回。
两个“之后”重复

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +GraphQL 不能脱离类型系统处理查询，让我们用一个类型系统的例子来说明一个查询的执行过程，在这一系列的文章中我们重复使用了这些类型，下文是其中的一部分
最后缺冒号

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +现在让我们用一个例子来描述当一个查询请求被执行的全过程
最后缺句号

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +您可以将 GraphQL 查询中的每个字段视为返回下一个类型的上一个类型的函数或方法。事实上，这正是 GraphQL 的工作原理。每个类型的每个字段都由称为解析器的函数支持，该函数由 GraphQL 服务器开发人员提供。当一个字段被执行时，相应的解析器被调用以产生下一个值。
原文的 resolver 是函数名，请保留不翻译

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +如果字段产生标量值，例如字符串或数字，则执行完成。但是，如果一个字段产生一个实体对象，则该查询将继续执行对应字段的解析器函数，直到生成标量值。GraphQL 查询始终以标量值结尾。
1. “产生一个实体对象” 的 “实体” 是哪儿来的？
2. 继续执行“该对象”对应字段的……
3. “以标量值结尾”=>“到标量值结束”

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +## 根字段&解析器函数
1. & 前后加空格
2. resolver 直接译作“解析器”
3. 前边空行太多了

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +每一个 GraphQL 服务端应用的顶层，必有一个类型代表着所有 GraphQL API的入口，我们将他称之为根类型或者查询类型。
1. 所有“进入” GraphQL API “可能”的入口点
2. Root 和 Query 是类型名，保留不翻译

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +```
js 也不要删掉，以便高亮代码，下同

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +在这个例子中查询类型提供了一个字段 `human`，并且接受一个参数 `id`。解析器函数请求了数据库并通过构造函数染回了 `Human` 对象。
“这个字段” 的解析器函数 “可能” 请求数据库，“之后构造并返回一个” `Human` 对象。

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +这个例子使用了 JavaScript 语言，但 GraphQL 服务端应用可以被 [多种语言实现](https://github.com/whisperfairy/graphql-china.github.io/blob/zh-cn/code) .无论哪种语言，解析器函数都接受3个参数
1. URL 路径请保持原状
2. “无论哪种语言”并无原文依据，请删除
3. “接受3个参数”=>“接收 3 个参数”
4. 最后缺一个句号

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +- `context` 会被提供了所有解析器，并且持有重要的上下文信息比如当前登入的用户或者数据库访问对象
“提供了”=>“提供给”

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +## 异步解析器函数
“函数”删去

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +让我们分析下下文中的解析器函数
1. “分析下下文”别扭，可考虑改成“让我们来分析一下在这个解析器函数中发生了什么。”
2. 最后缺句号

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +`context` 提供了一个数据库访问对象用来通过查询中传递的参数 `id` 来查询数据，因为从数据库拉去数据的过程是一个异步操作，该方法返回了一个 [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) 对象，在 JavaScript 语言中 Pro
1. “用来通过查询中……”前边加逗号
2. “拉去”=>“拉取”
3. “返回异步操作”=>“处理异步操作”
4. “但这个概念在各种语言中都有提及”=>“但在许多语言中存在相同的概念”
5. “比如”=>“通常称作”
6. “Futures” 等单词的斜体效果不要移除
7. “就能通过构造函数返回”=>“就能构造并返回”

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +这里要注意的是，只有解析器函数能感知到 Promise，GraphQL 查询只关注 `human` 字段是否返回，在执行期间如果异步操作没有完成，则 GraphQL 会一直等待下去，因此在这个环节需要关注异步处理上的优化。
1. “能感知到 Promise”=>“需要关注 Promise（的进度）”
2. “which it can then ask the `name` of”整句漏掉了

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +GraphQL 服务端应用的业务取决于类型系统的结构。在 `human` 对象返回值之前，GraphQL 会根据预设好的类型系统与对应的解析器函数决定如何以及返回什么样的Human字段。
太过意译了，跟原文几乎是两句话，这不符合翻译的原则

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +在这个例子中，对 name 字段的处理非常的清晰， name 字段对应的解析器函数调用了在上层回调函数生成的 `new Human` 对象在这个案例中，我们设计Human对象会拥有一个 `name` 属性可以让我们从 obj 对象中直接读取。
1. 第二个 name 和前边的逗号之间不加空格
2. name 字段对应的解析器函数“被调用”，不是“调用了”
3. “在这个案例中”前边加句号
4. “我们设计”=>“我们期望”
5. “从 obj 对象中”哪儿来的？

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +事实上在返回的字段可以直接从对象中获得的时候，大部分 GraphQL 库可以让我们省略定义的步骤，当然这是当我们请求的字段可以直接从上层返回对象中取得并返回的情况。
第一句和第三句意思重复，“if a resolver isn't provided for a field”又漏掉了

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +## 标准解析器
“Trivial” 是“不重要的”意思，不是“标准”

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +这是标量强制的一个例子。类型系统知道预期的内容，并将将解析器函数返回的值转换为维护 API 合同的内容。在这种情况下，可能在我们的服务器上定义了一个枚举类型，但解析器在内部使用 4,5 和 6 的整数类型，但在 GraphQL 类型系统中将它们表示为枚举值，如果类型不匹配将返回 null，并提示错误。
机翻，有些单词的意思明显不对，请重新润色下

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +我们已经看到一个字段返回上面的`appearsIn`字段的事物列表时会发生什么。它返回了枚举值的列表，因为这是系统期望的类型，列表中的每个项目被强制为适当的枚举值。让我们看下`startships`被解析的时候会发生什么？
1. 原文斜体的地方，翻译成中文后加粗
2. 英文前后加空格

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +解析器函数在这个字段中返回了一个 Promise 对象，它返回一个 Promises 列表。 `Human` 对象具有他们正在驾驶的 `Starships` 的 ids 列表，但是我们需要通过这些 id 来获得真正的 Starship 对象。
1. “解析器函数在这个字段中返回了一个 Promise 对象”=>“这个字段的解析器不仅仅是返回一个 Promise 对象”
2. “列表”加粗

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +GraphQL 将在同步执行这些 Promise，当返回一个对象列表，它将继续同步加载每个这些对象的 `name` 字段。
GraphQL 将 ~~在同步~~“并发” 执行 ~~这些~~“所有的” Promise，当返回一个对象列表“之后”，它将继续~~同步~~“并发”加载每个~~这些~~对象的 `name` 字段
觉得可以吗？

2017-08-15 06:59 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +当每个字段被解析时，结果值被放置到键值映射中，字段名称（或别名）作为键，并且解析器的值作为值，这继续从查询的底部叶字段返回直到根据“查询”类型的原始字段。总而言之，这些结构反映了原始查询，然后可以将其发送（通常为 JSON）到请求的客户端。
机翻，root Query type 明显不对

2017-08-16 05:47 UTC, whisperfairy commented on site/learn/Learn-Execution.md
> +在这个例子中，对 name 字段的处理非常的清晰， name 字段对应的解析器函数调用了在上层回调函数生成的 `new Human` 对象在这个案例中，我们设计Human对象会拥有一个 `name` 属性可以让我们从 obj 对象中直接读取。
关于问题4 ，这里的语境用设计是不是会更合适呢

2017-08-16 05:48 UTC, whisperfairy commented on site/learn/Learn-Execution.md
> +GraphQL 服务端应用的业务取决于类型系统的结构。在 `human` 对象返回值之前，GraphQL 会根据预设好的类型系统与对应的解析器函数决定如何以及返回什么样的Human字段。
有点拿捏不下，现在翻译成
GraphQL 服务端应用的业务取决于类型系统的结构。在 `human` 对象返回值之前，由于类型系统确定了 `human` 字段将返回一个 `Human` 对象，GraphQL 会根据类型系统预设好的 `Human` 类型决定如何解析字段。

2017-08-16 05:49 UTC, whisperfairy commented on site/learn/Learn-Execution.md
> +这是标量强制的一个例子。类型系统知道预期的内容，并将将解析器函数返回的值转换为维护 API 合同的内容。在这种情况下，可能在我们的服务器上定义了一个枚举类型，但解析器在内部使用 4,5 和 6 的整数类型，但在 GraphQL 类型系统中将它们表示为枚举值，如果类型不匹配将返回 null，并提示错误。
这里因为当时没看懂自己实际实现试了下，加了一点内容，这样可以吗
这是一个强制标量的例子。因为类型系统已经被设定，所以解析器函数的返回值必须符合与类型系统对应的API规则的约束。在这种情况下，我们在的服务器的类定义了一个应该返回枚举值解析器在内部返回了 4,5 和 6 的整数类型，由于 GraphQL 类型系统中将它们表示为枚举值，类型不匹配。因此实际的返回不是`[4,5,6]`而是`[null,null,null]`，并提示错误。

2017-08-16 08:38 UTC, ydfzgyj requested changes

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +在验证环节之后，GraphQL 服务端在处理数据，会根据 GraphQL 查询的请求内容生成对应结构的结果，一般情况下会以 JSON 形式返回。
删除第二个“之后”，也要重新调整一下语句，现在不甚通畅

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +您可以将 GraphQL 查询中的每个字段视为返回下一个类型的上一个类型的函数或方法。事实上，这正是 GraphQL 的工作原理。每个类型的每个字段都由称为 *resolver* 的函数支持，该函数由 GraphQL 服务器开发人员提供。当一个字段被执行时，相应的解析器被调用以产生下一个值。
还有一个 resolver

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +每一个 GraphQL 服务端应用的顶层，必有一个类型代表着所有进入 GraphQL API 可能的入口点，我们将他称之为*Root* 类型或 *Query* 类型。
1. Root 前面缺空格
2. “他”=>“它”，其他文章内的他和它也请统一

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +这个例子使用了 JavaScript 语言，但 GraphQL 服务端应用可以被 [多种语言实现](/code/) 。解析器函数接受 3 个参数：
1. “接受”=>“接收”
2. 句号前边无需加空格

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +这里要注意的是，只有解析器能感知到 Promise 的进度，GraphQL 查询只关注一个包含着`name`属性的 `human` 字段是否返回，在执行期间如果异步操作没有完成，则 GraphQL 会一直等待下去，因此在这个环节需要关注异步处理上的优化。
name 前后加空格

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
>  事实上在返回的字段可以直接从对象中获得的时候，大部分 GraphQL 库可以让我们省略定义的步骤，当然这是当我们请求的字段可以直接从上层返回对象中取得并返回的情况。
这一句没有改？

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +请注意，我们的类型系统声明 `appearsIn` 字段将返回具有已知值的枚举值，但是此函数返回数字实际上，如果我们查看结果，我们将看到正在返回适当的枚举值。这是怎么回事？
为什么这里把叹号删掉？

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +我们已经看到一个字段返回上面的 `appearsIn` 字段的事物列表时会发生什么。它返回了枚举值的*列表*，因为这是系统期望的类型，列表中的每个项目被强制为适当的枚举值。让我们看下`startships`被解析的时候会发生什么？
原文斜体的地方，翻译成中文后加粗，下同

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +这是一个强制标量的例子。因为类型系统已经被设定，所以解析器函数的返回值必须符合与类型系统对应的API规则的约束。在这种情况下，我们在的服务器的类定义了一个应该返回枚举值解析器在内部返回了 4,5 和 6 的整数类型，由于 GraphQL 类型系统中将它们表示为枚举值，类型不匹配。因此实际的返回不是`[4,5,6]`而是`[null,null,null]`，并提示错误。
1. API 前后加空格
2. “我们在的服务器的类定义了一个应该返回枚举值解析器在内部返回了 4、5 和 6 的整数类型” 整句完全不通
3. “由于 GraphQL 类型系统中将它们表示为枚举值，类型不匹配。因此实际的返回不是`[4,5,6]`而是`[null,null,null]`，并提示错误。” **这句的原文在哪里**？？？

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +GraphQL 将在并发执行这些 Promise，当执行结束返回一个对象列表后，它将继续并发加载列表中每个对象的 `name` 字段。
第一个“在”字去掉

2017-08-16 08:38 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +当每个字段被解析时，结果被放置到键值映射中，字段名称（或别名）作为键值映射的键，解析器的值作为键值映射的值，这个过程从查询字段的底部叶子节点开始返回，直到根查询类型的根字段。总而言之，这些结构反映了根查询类型，然后可以将其发送（通常为 JSON 格式）到请求的客户端。
1. original 和 root 不是一回事
2. root Query type 的 Query 不翻译
3. “总而言之，这些结构反映了根查询类型”=>“最后合并成为能够镜像到原始查询结构的结果”

2017-08-16 10:04 UTC, jonirrings commented on site/learn/Learn-Execution.md
> +在验证环节之后，GraphQL 服务端在处理数据，会根据 GraphQL 查询的请求内容生成对应结构的结果，一般情况下会以 JSON 形式返回。
在验证环节之后，GraphQL 服务端在处理数据，
->
在验证环节之后，GraphQL 服务端在处理数据时，

感觉这样顺口些

2017-08-17 12:13 UTC, ydfzgyj requested changes

2017-08-17 12:13 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +每一个 GraphQL 服务端应用的顶层，必有一个类型代表着所有进入 GraphQL API 可能的入口点，我们将它称之为 **Root** 类型或 **Query** 类型。
英文可以保留斜体，翻译成中文的才要改成加粗

2017-08-17 12:13 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +事实上在返回的字段可以直接从对象中获得的时候，大部分 GraphQL 库可以让我们省略定义的步骤，当然这只适用于我们请求的字段可以直接从上层返回对象中取得并返回的情况。
这一句还是没有改好
第一句“返回的字段可以直接从对象中获得”和第三句“我们请求的字段可以直接从上层返回对象中取得并返回”是一样的话，重复说了两遍，是多余的
而原文的“if a resolver isn't provided for a field”又根本没有译，“没有提供解析器”所以才只能从“上层对象中读取”，这是因果关系，不可以省去的

2017-08-17 12:13 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +当每个字段被解析时，结果被放置到键值映射中，字段名称（或别名）作为键值映射的键，解析器的值作为键值映射的值，这个过程从查询字段的底部叶子节点开始返回，直到根 Query 类型的起始节点。总而言之，这些结构反映了根 Query 类型，然后可以将其发送（通常为 JSON 格式）到请求的客户端。
1. original 和 root 不是一回事
2. “总而言之，这些结构反映了根查询类型”=>“最后合并成为能够镜像到原始查询结构的结果”

2017-08-17 12:13 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +这是一个强制标量的例子。因为类型系统已经被设定，所以解析器函数的返回值必须符合与类型系统对应的API规则的约束。在这种情况下，我们在的服务器的类定义了一个应该返回枚举值解析器在内部返回了 4、5 和 6 的整数类型，但是 GraphQL 类型系统中将它们表示为枚举值。
1. API 前后加空格
2. “我们在的服务器的类定义了一个应该返回枚举值解析器在内部返回了 4、5 和 6 的整数类型” 整句不通，可以改成
“在这个案例中， 我们可能在服务器上定义了一个枚举类型，它在内部使用像是 4、5 和 6 这样的数字，但在 GraphQL 类型系统中将它们表示为枚举值。”

2017-08-17 12:31 UTC, jonirrings commented
:joy: 看来这块儿骨头比较硬啊

2017-08-17 15:09 UTC, ydfzgyj requested changes
还差一点点

2017-08-17 15:09 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +这是一个强制标量的例子。因为类型系统已经被设定，所以解析器函数的返回值必须符合与类型系统对应的 API 规则的约束。在这个案例中， 我们可能在服务器上定义了一个枚举类型，它在内部使用像是 4、5 和 6 这样的数字，但在 GraphQL 类型系统中将它们表示为枚举值。
“我们可能……”前边的空格去掉

2017-08-17 15:09 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
>  让我们最后一眼看看原来的查询，看看这些解析函数如何产生一个结果：
最后的一段代码怎么删掉了

2017-08-17 15:09 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +
这个多余的空行去掉

2017-08-17 15:09 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +当每个字段被解析时，结果被放置到键值映射中，字段名称（或别名）作为键值映射的键，解析器的值作为键值映射的值，这个过程从查询字段的底部叶子节点开始返回，直到根 Query 类型的起始节点。总而言之，最后合并成为能够镜像到原始查询结构的结果，然后可以将其发送（通常为 JSON 格式）到请求的客户端。
“总而言之，”去掉

2017-08-17 15:09 UTC, ydfzgyj commented on site/learn/Learn-Execution.md
> +事实上在返回的字段可以直接从对象中获得并且没有额外定义解析器的时候，大部分 GraphQL 库可以让我们省略定义的步骤。
意思还是有偏差……没有体现出“没有定义解析器再去读取对象”的先后关系
可译为：“事实上，许多 GraphQL 库可以让你省略这些简单的解析器，假定一个字段没有提供解析器时，那么应​​该从上层返回对象中读取和返回和这个字段同名的属性。”

2017-08-17 15:30 UTC, ydfzgyj approved these changes

2017-08-17 15:31 UTC, ydfzgyj commented
终于完成啦，撒花～🎉🎉🎉

2017-08-17 15:33 UTC, whisperfairy commented
不好意思耽误您这么长时间。

2017-08-17 15:33 UTC, whisperfairy commented
谢谢您的指导

2017-08-17 15:46 UTC, merged