learn validation翻译完成
xitu/graphql.github.io pull request #56
Opened 2017-08-02 05:52 UTC by jonirrings

pr晚了，有劳校对

2017-08-02 07:02 UTC, jonirrings reviewed
需要校对

2017-08-02 07:02 UTC, jonirrings commented on site/learn/Learn-Validation.md
> +类似的，如果一个字段是标量，进一步查询它上面的字段也没有意义，这样做也会导致查询无效：
类似的，类似地。
把握不准，前者是“类似的情况下”的简略写法，后者是状语副词，好像也适合这个场景。有劳校对指教。

2017-08-02 13:12 UTC, ydfzgyj requested changes

2017-08-02 13:12 UTC, ydfzgyj commented on site/learn/Learn-Validation.md
> +对于我们的《星球大战》的案例，[starWarsValidation-test.js](https://github.com/graphql/graphql-js/blob/master/src/__tests__/starWarsValidation-test.js)这个文件包含一些查询，演示了各种无效查询，它也是一个测试文件，用于检测参考实现的验证器。
1. 链接和中文之间加上一个空格
2. “包含一些查询，演示了各种无效查询” => “包含了若干对于各种无效查询的演示”

2017-08-02 13:12 UTC, ydfzgyj commented on site/learn/Learn-Validation.md
> +查询字段的时候，我们只能查询给定类型上的字段。因此由于 `hero` 返回 `Character`类型，我们只能查询 `Character` 上的字段。因为这个类型上没有 `favoriteSpaceship` 字段，所以这个查询是无效的：
第一个`Character`后加空格

2017-08-02 13:12 UTC, ydfzgyj commented on site/learn/Learn-Validation.md
>  # { "graphiql": true }
这里也有一句注释，下面还有几处，就不重复了

2017-08-02 13:12 UTC, ydfzgyj commented on site/learn/Learn-Validation.md
>  # { "graphiql": true }
这里有一句注释也翻译一下吧

2017-08-02 13:12 UTC, ydfzgyj commented on site/learn/Learn-Validation.md
> +当我们查询一个字段时，如果其返回值不是标量或者枚举型，那我们就需要指明想要从这个字段中获取的数据。`hero` 返回 `Character`类型，我们也请求了像是 `name` 和`appearsIn` 的字段；但如果将其省略，这个查询就变无效的了：
1. 第一个`Character`后加空格
2. 我们也请求了“其中”像是……
3. 这个查询就变“成”无效的了

2017-08-02 13:12 UTC, ydfzgyj commented on site/learn/Learn-Validation.md
> +类似的，如果一个字段是标量，进一步查询它上面的字段也没有意义，这样做也会导致查询无效：
原文是副词，这里就用“类似地”就好吧

2017-08-02 13:12 UTC, ydfzgyj commented on site/learn/Learn-Validation.md
> +这只是验正系统的冰山一角；事实上需要一大套验正规则才能保证 GraphQL 查询的语义意义。规范中的“验证”章节有关于本话题更详细的内容，GraphQL.js 的 [validation](https://github.com/graphql/graphql-js/blob/master/src/validation) 目录包含了规范兼容的 GraphQL 验证器实现代码。
“验正”=>“验证”，不是换成五笔了么😂

2017-08-03 01:44 UTC, jonirrings commented on site/learn/Learn-Validation.md
> +这只是验正系统的冰山一角；事实上需要一大套验正规则才能保证 GraphQL 查询的语义意义。规范中的“验证”章节有关于本话题更详细的内容，GraphQL.js 的 [validation](https://github.com/graphql/graphql-js/blob/master/src/validation) 目录包含了规范兼容的 GraphQL 验证器实现代码。
换了，这可能是脑子没转过去。:joy:

2017-08-03 01:51 UTC, jonirrings commented
已修正，有劳再次审核

2017-08-03 07:58 UTC, ydfzgyj requested changes

2017-08-03 07:58 UTC, ydfzgyj commented on site/learn/Learn-Validation.md
> +这只是验正系统的冰山一角；事实上需要一大套验证规则才能保证 GraphQL 查询的语义意义。规范中的“验证”章节有关于本话题更详细的内容，GraphQL.js 的 [validation](https://github.com/graphql/graphql-js/blob/master/src/validation) 目录包含了规范兼容的 GraphQL 验证器实现代码。
第五个字，还有一个“验正”

2017-08-03 08:11 UTC, jonirrings commented on site/learn/Learn-Validation.md
> +这只是验正系统的冰山一角；事实上需要一大套验证规则才能保证 GraphQL 查询的语义意义。规范中的“验证”章节有关于本话题更详细的内容，GraphQL.js 的 [validation](https://github.com/graphql/graphql-js/blob/master/src/validation) 目录包含了规范兼容的 GraphQL 验证器实现代码。
:joy:,又漏了，已修正。

2017-08-03 08:17 UTC, ydfzgyj approved these changes

2017-08-10 04:14 UTC, linhe0x0 approved these changes

2017-08-10 04:15 UTC, merged