API 参考-执行
xitu/graphql.github.io pull request #57
Opened 2017-08-02 17:33 UTC by XatMassacrE

原  Issues [#13](https://github.com/xitu/graphql.github.io/issues/14)

2017-08-03 02:14 UTC, jonirrings requested changes
需要讨论细节

2017-08-03 02:14 UTC, jonirrings commented on site/graphql-js/APIReference-Execution.md
> +      对定义好的 schema 执行一个 GraphQL 请求。
provided这个词能不能翻译成“给定”，或者“现有”？讨论讨论~~~

2017-08-03 02:14 UTC, jonirrings commented on site/graphql-js/APIReference-Execution.md
> +上面的代码实现了 GraphQL 规范中评估请求“的部分。
evaluate其实更多是“演算，求值”，譬如evaluate a function。对应中文一起讨论讨论。

2017-08-03 02:14 UTC, jonirrings commented on site/graphql-js/APIReference-Execution.md
> +如果这个函数的参数导致产生了一个非法的执行上下文，那么马上就会有一个解释非法输入的 GraphQLError 被抛出。
1. “导致”和“产生”重复。
2. 那么马上就会有一个 GraphQLError 被抛出，表示非法输入。

你看如何？

2017-08-07 16:56 UTC, XatMassacrE commented on site/graphql-js/APIReference-Execution.md
> +      对定义好的 schema 执行一个 GraphQL 请求。
翻译成”给定“吧。
对给定的 schema 执行一个 GraphQL 请求。

2017-08-07 17:01 UTC, XatMassacrE commented on site/graphql-js/APIReference-Execution.md
> +上面的代码实现了 GraphQL 规范中评估请求“的部分。
翻译成”构建请求“怎么样？

2017-08-07 17:11 UTC, XatMassacrE commented on site/graphql-js/APIReference-Execution.md
> +如果这个函数的参数导致产生了一个非法的执行上下文，那么马上就会有一个解释非法输入的 GraphQLError 被抛出。
1. 如果这个函数的参数造成了一个非法的执行上下文
2. 那么马上就会有一个 GraphQLError 被抛出，这个错误将会解释非法输入的具体信息。（引文前面的章节提到 GraphQLError 包含一些 location 和 info，这个地方这么翻译更清楚一点）

2017-08-07 17:12 UTC, XatMassacrE commented
@jonirrings 麻烦看下修改意见，如果没问题的话，我就按照我的回复再提交一个修订版，如果有问题继续在对话框里面讨论。

2017-08-08 00:37 UTC, jonirrings commented on site/graphql-js/APIReference-Execution.md
> +上面的代码实现了 GraphQL 规范中评估请求“的部分。
构建请求不适合，因为请求是在客户端构建，服务端处理来自客户端的请求，这里是服务端，直接翻译成 处理请求 如何?

2017-08-08 00:37 UTC, jonirrings commented on site/graphql-js/APIReference-Execution.md
> +如果这个函数的参数导致产生了一个非法的执行上下文，那么马上就会有一个解释非法输入的 GraphQLError 被抛出。
nice

2017-08-08 00:37 UTC, jonirrings commented
@XatMassacrE 回复了，你瞅瞅

2017-08-08 13:53 UTC, XatMassacrE commented
@jonirrings 感谢校对。

2017-08-08 13:55 UTC, XatMassacrE commented
@sqrthree 按照校对意见修改完毕。

2017-08-08 14:06 UTC, sqrthree commented on site/graphql-js/APIReference-Execution.md
> +上面的代码实现了 GraphQL 规范中”处理请求“的部分。
『”处理请求“』你这俩标点是不是反了？

2017-08-09 02:47 UTC, XatMassacrE commented on site/graphql-js/APIReference-Execution.md
> +上面的代码实现了 GraphQL 规范中”处理请求“的部分。
咦... 好像是唉

2017-08-09 14:42 UTC, XatMassacrE commented
@sqrthree 改好啦

2017-08-09 15:31 UTC, linhe0x0 approved these changes

2017-08-09 15:32 UTC, sqrthree commented
@jonirrings 需要你来检查并 approve 一下。

2017-08-10 07:48 UTC, jonirrings approved these changes

2017-08-10 07:48 UTC, merged