APIReference-GraphQL.md
xitu/graphql.github.io pull request #59
Opened 2017-08-04 07:44 UTC by llp0574

@sqrthree 搞定一篇，close #16

2017-08-04 19:40 UTC, ydfzgyj requested changes
需要根据 Wiki 里的 [翻译术语表](https://github.com/xitu/graphql.github.io/wiki/%E7%BF%BB%E8%AF%91%E6%9C%AF%E8%AF%AD%E8%A1%A8) 和 [翻译规范指南](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97) 做一些小调整

2017-08-04 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-GraphQL.md
> +`graphql` 模块导出了 GraphQL 的一个核心子集，其主要功能是创建 GraphQL 类型的系统和服务。
“GraphQL 类型的系统” =>“GraphQL 的类型系统”

2017-08-04 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-GraphQL.md
> +*入口点（Entry Point）*
翻译成中文的斜体字替换成粗体字

2017-08-04 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-GraphQL.md
> +详细介绍请看[类型系统 API 参考](../type#schema)。
链接和其他文字中间加上空格

2017-08-04 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-GraphQL.md
> +*模式（Schema）*
Schema 这个词不翻译

2017-08-04 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-GraphQL.md
> +      GraphQL 里的标量类型。（译者注：表示最细粒度数据结构的数据类型，可以和 JavaScript 的原始类型对应）
感谢详细的译者注，但这里实际上是一个 API 总目录，所以用户不清楚的地方可以点击进去看更多的详细说明，所以这里的内容最好还是以简要介绍为主

2017-08-04 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-GraphQL.md
> +      根据一个模式（schema）lex（译者注：这里主要指使用 GraphQL 的 lex 方法生成一个 Lexer，后面的 lex 同理）、解析、验证及执行一个 GraphQL 请求。
可以考虑把 lex 直接翻译成“词法分析”吗？

2017-08-08 02:17 UTC, llp0574 commented
感谢 @ydfzgyj 校对意见，已修改提交。

2017-08-08 03:05 UTC, sqrthree commented on site/graphql-js/APIReference-GraphQL.md
> +*标量类型*
斜体请改为加粗形式。

2017-08-08 03:05 UTC, sqrthree commented on site/graphql-js/APIReference-GraphQL.md
> +*错误信息*
同上，斜体问题。

2017-08-08 03:05 UTC, sqrthree commented on site/graphql-js/APIReference-GraphQL.md
> +`graphql` 方法可以对一个 GraphQL 请求进行词法分析、解析、验证和执行。必要的参数是 `schema` 和 `requestString`，可选的参数则包括 `rootValue`（将作为根值传入执行器方法）、`contextValue`（将传入所有的解析函数）、`variableValues`（将传入执行器方法，为 `requestString` 中的任意类型变量赋值）以及 `
建议这一行上面加一个空行，和上面的代码段区分开。

2017-08-08 07:52 UTC, ydfzgyj approved these changes

2017-08-09 12:43 UTC, linhe0x0 approved these changes

2017-08-09 12:43 UTC, merged

2017-08-10 02:06 UTC, llp0574 commented
@sqrthree 这一篇开头的 category 和 sublink 我还没有翻，最后记得统一一下。

2017-08-10 02:48 UTC, sqrthree commented
category 他们翻译成了『API 参考』，你这篇的 sublink 不需要翻译。

2017-08-10 02:51 UTC, llp0574 commented
那是否需要我再翻译了提交一次？

2017-08-10 02:57 UTC, sqrthree commented
好