Tutorial Authentication translation done
xitu/graphql.github.io pull request #60
Opened 2017-08-04 09:38 UTC by jonirrings

2017-08-04 19:37 UTC, ydfzgyj requested changes

2017-08-04 19:37 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Authentication.md
> +在 REST API 中，认证通常是借由 header 处理的，其中包含一个 auth token 用于识别发出请求的用户。Express 中间件会处理这些 header，并将认证数据放进 Express 的 `request` 对象。如此处理认证的中间件模块有 [Passport](http://passportjs.org/), [express-jwt](https://github.co
1. 可以换成顿号
2. 每一个“都”能配合

2017-08-04 19:37 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Authentication.md
> +你可以就像普通 Express 应用使用中间件一样把中间件和 GraphQL 解析器一起使用。然后 `request` 对象就会作为解析函数的第二参数传入。（译者案：[v0.5.0](https://github.com/graphql/graphql-js/releases/tag/v0.5.0) 之后，作为第三参数）
译者注是统一这么写？还是用脚注？我研究了一下，[这里](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97#%E5%A6%82%E6%9E%9C%E6%96%87%E7%AB%A0%E4%B8%AD%E6%9C%89%E8%84%9A%E6%B3%A8%E6%80%8E%E4%B9%88%E5%8A%9E) 的方案改一点代码可以实现

2017-08-04 19:37 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Authentication.md
> +举个例子，假设我们想要服务器记录每个请求的 IP 地址，并编写一个返回调用者 IP 地址的 API。前者我们通过中间件完成，后者则通过在解析器中取 `request` 对象即可。下面是实现这个功能的服务端代码：
“后者则……”这句的“通过”和“即可”留一个就好

2017-08-05 05:05 UTC, jonirrings commented on site/graphql-js/Tutorial-Authentication.md
> +举个例子，假设我们想要服务器记录每个请求的 IP 地址，并编写一个返回调用者 IP 地址的 API。前者我们通过中间件完成，后者则通过在解析器中取 `request` 对象即可。下面是实现这个功能的服务端代码：
嗯嗯，当时是有点觉得不对劲

2017-08-05 05:06 UTC, jonirrings commented on site/graphql-js/Tutorial-Authentication.md
> +你可以就像普通 Express 应用使用中间件一样把中间件和 GraphQL 解析器一起使用。然后 `request` 对象就会作为解析函数的第二参数传入。（译者案：[v0.5.0](https://github.com/graphql/graphql-js/releases/tag/v0.5.0) 之后，作为第三参数）
我们得看看这个md的工具支持脚注不……

2017-08-05 06:06 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Authentication.md
> +你可以就像普通 Express 应用使用中间件一样把中间件和 GraphQL 解析器一起使用。然后 `request` 对象就会作为解析函数的第二参数传入。（译者案：[v0.5.0](https://github.com/graphql/graphql-js/releases/tag/v0.5.0) 之后，作为第三参数）
我开个 issue 讨论一下

2017-08-05 06:17 UTC, ydfzgyj approved these changes
除了译者注需再讨论外，没有问题了

2017-08-05 07:49 UTC, jonirrings commented
@ydfzgyj 那就开个issue吧，想想怎么组织内容……

2017-08-07 14:35 UTC, sqrthree commented on site/graphql-js/Tutorial-Authentication.md
> +在 REST API 中，认证通常是借由 header 处理的，其中包含一个 auth token 用于识别发出请求的用户。Express 中间件会处理这些 header，并将认证数据放进 Express 的 `request` 对象。如此处理认证的中间件模块有 [Passport](http://passportjs.org/)、 [express-jwt](https://github.co
『如此处理认证的中间件模块』要不改成『如果此处理认证的中间件模块』或『如该处理认证的中间件模块』，避免造成断句上的困扰？

2017-08-07 15:13 UTC, jonirrings commented on site/graphql-js/Tutorial-Authentication.md
> +在 REST API 中，认证通常是借由 header 处理的，其中包含一个 auth token 用于识别发出请求的用户。Express 中间件会处理这些 header，并将认证数据放进 Express 的 `request` 对象。如此处理认证的中间件模块有 [Passport](http://passportjs.org/)、 [express-jwt](https://github.co
好的。

2017-08-07 16:35 UTC, ydfzgyj approved these changes

2017-08-10 04:21 UTC, linhe0x0 approved these changes

2017-08-10 04:22 UTC, merged