"APIReference-TypeSystem.md" 初稿
xitu/graphql.github.io pull request #61
Opened 2017-08-05 04:59 UTC by hikerpig

Close [issue 18](https://github.com/xitu/graphql.github.io/issues/18)

感觉翻得有些词不达意，类似于 Composite 这种设计模式里的东西，懂的人自然懂，不懂的话照着原文里的简单说明去翻基本上也是云里雾里。

麻烦校对了

2017-08-05 08:11 UTC, jonirrings reviewed
细节需要讨论

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +title: graphql/type 类型系统
这个是api……其实建议保持原样……:joy:

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +`graphql/type` 模块的职责为定义 GraphQL 的类型和 schemea。你可以从 `graphql/type` 模块或是根模块 `graphql` 引入。例如：
schemea -> schema

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +      类型包装器，表示被包装类型取值不为 null 的版本。
`non-null` 我是翻译作 `非空` 或者 `不可为空`。你参考下

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +      判断某类型是否为组合类型，即是否可作为参加组合的叶节点的父节点。
判断某类型是否为一个选择集的父级上下文。
selection set这个我们可能需要讨论下
`即是`后面的部分是不是可以作为传说中的`译者案`？

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +      判断某类型是否为抽象类型，即是否可代表其一系列 Object 类型实现。
…这意译和原文 词语的对应关系好远。
直译感觉也行啊。
判断某类型是否为对象类型的组合。

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +*去包装函数（Un-modifiers）*
modifier我记得是翻译作修饰符，修饰器，要不统一一下？

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +使用指定的 query 及 mutation（可选）的根类型来创建Schema。生成的 Schema 可用于之后的校验器和执行器。
validator这个词我们也需要统一一下，验证器，还是校验器。

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +当两个类型需要相互指涉，或是某类型需要的某一字段类型为其自身，你可以使用函数表达式（也可称为闭包或是 thunk）来实现字段类型的延后求值。
refer，不妨翻译作`引用`

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
>  #### Example
咦，漏了个example没翻译，前后都有翻译来着

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
>  Some leaf values of requests and input values are Enums. GraphQL serializes
忘记删了

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +一个输入对象类型定义了一群可以作为某字段查询参数的字段。
一群 -> 一组，如何？

2017-08-05 08:11 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +判断某类型是否为组合类型，即是否可作为参加组合的叶节点的父节点。
同上。

2017-08-05 11:24 UTC, hikerpig commented on site/graphql-js/APIReference-TypeSystem.md
> +*去包装函数（Un-modifiers）*
改为“去包装修饰符”如何？modifier 倒是好说，主要是 un 的意思

2017-08-05 11:31 UTC, hikerpig commented on site/graphql-js/APIReference-TypeSystem.md
> +使用指定的 query 及 mutation（可选）的根类型来创建Schema。生成的 Schema 可用于之后的校验器和执行器。
是的，这个是需要放到术语表里的。我个人觉得校验器比较舒服一点，最后如何看大家讨论的意见吧。
顺带说一句， front-matter 里面 sublink 的翻译也需要统一

2017-08-05 11:36 UTC, hikerpig commented on site/graphql-js/APIReference-TypeSystem.md
> +当两个类型需要相互指涉，或是某类型需要的某一字段类型为其自身，你可以使用函数表达式（也可称为闭包或是 thunk）来实现字段类型的延后求值。
这个地方我有考虑过，我的感觉是“引用”比较适合用作 `reference` 的翻译，类似于“引用变量”，“对该对象的引用”。此处是类型系统里的概念，不过“指涉”的确是有点太生僻了，不知 “指代” 会不会更好点？

2017-08-05 11:44 UTC, hikerpig commented on site/graphql-js/APIReference-TypeSystem.md
> +      判断某类型是否为抽象类型，即是否可代表其一系列 Object 类型实现。
这个地方和 CompositeType 纠结了很久。

不好意思，但是真的是我想太多了，看了下代码的实现，直译完全是对的。

``` javascript
/**
 * These types may describe the parent context of a selection set.
 */
export type GraphQLAbstractType =
  GraphQLInterfaceType |
  GraphQLUnionType;

export function isAbstractType(type: ?GraphQLType): boolean %checks {
  return (
    type instanceof GraphQLInterfaceType ||
    type instanceof GraphQLUnionType
  );
}
```

2017-08-05 11:50 UTC, hikerpig commented on site/graphql-js/APIReference-TypeSystem.md
> +title: graphql/type 类型系统
我感觉正因为是 api，才应该把后面的 `s` 去掉，正文第一句话就说了 `graphql/type` 模块，这个复数形式这么放感觉有点误导

2017-08-05 11:59 UTC, hikerpig commented on site/graphql-js/APIReference-TypeSystem.md
> +      判断某类型是否为组合类型，即是否可作为参加组合的叶节点的父节点。
回来看了下源码感觉自己脑子进水想太多了，“选择集”挺好的，感谢。
最后为了和上文的啰嗦形式统一，准备改为“判断某类型是否可以作为一个选择集的父级上下文”

2017-08-05 12:10 UTC, hikerpig commented on site/graphql-js/APIReference-TypeSystem.md
> +title: graphql/type 类型系统
哦你说的也对，还是保留 title 吧，然后我去提个 pull request ...

2017-08-05 19:40 UTC, ydfzgyj requested changes

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +*定义（Definitions）*
由于翻译规范要求所有翻译成中文的斜体都改成加粗，但是这里还存在一个并列关系的不翻译的 Schema，因此建议对于所有出现在 ul 元素之前的斜体小标题，采用以下两种二选一：
1. 全部替换成加粗
2. 全部保留英文不翻译

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +      GraphQL 中的枚举类型，定义一个有效值的列表。
这一句和上一句同是 a list of，为什么翻译不一致呢？表达的意思并无不同呀

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +      判断某类型是否可以作为字段查询参数。
directives 漏掉了

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +      判断某类型是否可以作为字段查询结果的值。
be used as output **types**，还是作为类型，不是作为值

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +      整型数标量类型。
“整型数”怪怪的，跟浮点数对应的话直接“整数”就好，另外可以多写几个字的，比如“表示整数的标量类型”，读起来更舒服

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +使用指定的 query 及 mutation（可选）的根类型来创建Schema。生成的 Schema 可用于之后的校验器和执行器。
1. 校验器可以的
2. 第一个 Schema 前边需要加一个空格
3. 我觉得前半句表达的意思应该是 query 和 mutation 二选一来作为 schema 的根类型，译文感觉没有体现出来这一点

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +构建用于表示请求的叶节点值和输入值的标量（或枚举）类型 `GraphQLScalarType` 时，需要指定 `name` 以及一系列用于确保值的有效性的序列化函数。
GraphQLScalarType 和枚举没有关系呀，这里的意思是“这些值必须是标量或枚举”，并不需要加上“构建类型”这些东西

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +当一个字段可能返回多种不同类型时，可使用接口类型 `GraphQLInterfaceType`，来描述这些可能类型有什么共同字段，也可指定 `resolveType` 函数来决定该字段实际被解析时为何种类型。
“来描述这些可能类型有什么共同字段”这一句建议强调一下“所有可用类型共用的字段”，现在和 Union Type 的描述无法体现区分度

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +当一个字段可以返回多种不同类型时，可使用联合类型 `GraphQLUnionType` 描述所有可能类型，也可指定 `resolveType` 函数该字段实际被解析时为何种类型。
……函数“来确定”该字段……

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +一些请求的叶节点值和输入值为枚举类型。GraphQL 会将枚举值序列化为字符串，但在内部使用时，枚举值可以用任何类型来表示，一般用整型来表示。
前边两段翻译的时候加上了比如 `GraphQLUnionType` 之类的类型名进去，从这段开始又没加了，建议保持统一，要么都加，要么都不加

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +使用 `NonNull` 标明查询一定会有返回值。
ensure 漏了

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +## 谓词函数
目录部分用括号补充了原单词，这里请保持统一

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +判断某类型是否可以作为字段查询参数。
？？？复制过来的？意思完全不对啊

2017-08-05 19:40 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +判断某类型是否为对象类型的组合。
以上几段请重新翻译一下……

2017-08-06 02:39 UTC, hikerpig commented on site/graphql-js/APIReference-TypeSystem.md
> +使用指定的 query 及 mutation（可选）的根类型来创建Schema。生成的 Schema 可用于之后的校验器和执行器。
实际的运用以及 flow 的标注表示的应该都是二者都可指定，不是二选一 @ydfzgyj

2017-08-06 03:20 UTC, hikerpig commented on site/graphql-js/APIReference-TypeSystem.md
> +构建用于表示请求的叶节点值和输入值的标量（或枚举）类型 `GraphQLScalarType` 时，需要指定 `name` 以及一系列用于确保值的有效性的序列化函数。
是的，顺嘴提了一句的枚举的确不应该乱入，改为:

请求的叶节点值和输入值可以为标量（或枚举）类型。构建标量类型 `GraphQLScalarType` 时，需要指定 `name` 以及一系列用于确保值的有效性的序列化函数。

2017-08-06 03:56 UTC, hikerpig commented on site/graphql-js/APIReference-TypeSystem.md
> +判断某类型是否可以作为字段查询参数。
好的，漏翻和错误的地方修改了一下。
除去原先翻译错误的部分，我觉得这部分可以直接从目录里复制过来，原文里主要描述与目录都是一样的。而且原文中此处的 "These types may describe" 没有传达出谓词函数的用意。
和目录中保持一致翻为 “判断某类型是否可以作为字段查询参数和指令的输入类型” 如何？

2017-08-06 06:56 UTC, jonirrings commented on site/graphql-js/APIReference-TypeSystem.md
> +*去包装函数（Un-modifiers）*
就这么干~~~

2017-08-07 13:11 UTC, ydfzgyj commented on site/graphql-js/APIReference-TypeSystem.md
> +使用指定的 query 及 mutation（可选）的根类型来创建Schema。生成的 Schema 可用于之后的校验器和执行器。
我的错，我跟 query 那边混淆了……

2017-08-07 13:14 UTC, ydfzgyj approved these changes

2017-08-07 13:23 UTC, jonirrings submitted a review, later dismissed

2017-08-08 00:45 UTC, jonirrings commented
validator翻译成 校验器 和 验证器 方面 #65 讨论下，

2017-08-10 04:37 UTC, linhe0x0 approved these changes

2017-08-10 04:38 UTC, merged