Tutorial-Mutations.md
xitu/graphql.github.io pull request #66
Opened 2017-08-07 04:16 UTC by jonirrings

有劳校对

2017-08-07 17:01 UTC, ydfzgyj requested changes

2017-08-07 17:01 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Mutations.md
> +将一个变更（mutation）映射到数据库的 create 或者 update 操作会很方便，如 `setMessage`，其会返回数据库所存的数据。这样一来，你修改了服务端的数据，客户端就能获知这个修改
最后的句号

2017-08-07 17:01 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Mutations.md
> +不论变更还是查询，根级解析器能够处理，因此实现 schema 的 root 可以如下：
不论“是”变更还是查询，根级解析器“都”能够处理

2017-08-07 17:01 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Mutations.md
> +实现变更不必需要更多的东西。但是更多情况下，你会发现有多个不同的变更接受相同的输入参数。常见的案例是在数据库中创建对象和更新对象的接口就会接受一样的参数。你可以使用“输入类型”来简化 schema，使用 `input` 关键字而不是 `type` 关键字即可。
1. “不必需要”冗余，“不需要”即可
2. often 漏了

2017-08-07 17:01 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Mutations.md
> +一个有用的习惯是在末尾使用 `Input` 命名输入类型，因为通常对于一个单一概念对象你会有类似的输入和输出类型。
1. “习惯”=>“惯例”
2. “在末尾使用 `Input` 命名输入类型”似乎有歧义，“为输入类型命名时在末尾使用 `Input`”好一点
3. “slightly different” 应该是不同吧，怎么翻译成“类似”了

2017-08-07 17:01 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Mutations.md
> +你也像查询一样使用变量来简化变更的客户端逻辑。如下调用服务端变更的 JavaScript 代码：
你也“可以”像查询一样

2017-08-07 17:01 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Mutations.md
> +一个十分特殊变更类型是“改变用户”，譬如注册新用户。你能使用 GraphQL 变更实现这个功能，在学完 [GraphQL 认证和 Express 中间件](/graphql-js/authentication-and-express-middleware/) 之后你也能使用现有库来实现。
1. 十分特殊“的”变更类型
2. “除了使用 GraphQL 变更来实现这个功能之外”

2017-08-08 00:31 UTC, jonirrings commented on site/graphql-js/Tutorial-Mutations.md
> +一个有用的习惯是在末尾使用 `Input` 命名输入类型，因为通常对于一个单一概念对象你会有类似的输入和输出类型。
“slightly different”,略微不懂，我就翻译成相似了。那还是弄回来把。

2017-08-08 00:33 UTC, jonirrings commented on site/graphql-js/Tutorial-Mutations.md
> +一个有用的习惯是在末尾使用 `Input` 命名输入类型，因为通常对于一个单一概念对象你会有类似的输入和输出类型。
在末尾使用 Input 命名输入类型，这个末尾是指schema文本的末尾，一般先声明type后声明input。我补充一下嘛

2017-08-08 00:34 UTC, jonirrings commented on site/graphql-js/Tutorial-Mutations.md
> +一个十分特殊变更类型是“改变用户”，譬如注册新用户。你能使用 GraphQL 变更实现这个功能，在学完 [GraphQL 认证和 Express 中间件](/graphql-js/authentication-and-express-middleware/) 之后你也能使用现有库来实现。
已修正，有劳再次审校。

2017-08-08 03:55 UTC, ydfzgyj requested changes

2017-08-08 03:55 UTC, ydfzgyj commented on site/graphql-js/Tutorial-Mutations.md
> +一个有用的惯例是在 schema 的末尾使用 `Input` 命名输入类型，因为通常对于一个单一概念对象你的输入和输出类型只是略微不同。
原文是"you will often want ... are slightly different for ..."
我的理解意思应该是为 input types 类型命名加上 Input 的目的是把它和 output types 区分开来

2017-08-08 05:28 UTC, jonirrings commented on site/graphql-js/Tutorial-Mutations.md
> +一个有用的惯例是在 schema 的末尾使用 `Input` 命名输入类型，因为通常对于一个单一概念对象你的输入和输出类型只是略微不同。
graphql schema中的type就是标识output type，而input就是标识input type的。我好想把“想要”翻译漏了

2017-08-10 05:12 UTC, linhe0x0 approved these changes

2017-08-10 05:13 UTC, merged