Tutorial-GraphQLClients.md
xitu/graphql.github.io pull request #67
Opened 2017-08-07 06:27 UTC by jonirrings

有劳审校

2017-08-07 17:24 UTC, ydfzgyj requested changes
一些语句可以再润色一下，多加一些副词修饰一下，感觉有点干

2017-08-07 17:24 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GraphQLClients.md
> +由于 GraphQL API 拥有比 REST API 更多的下层结构，它也有更强大的客户端。辟如 [Relay](https://facebook.github.io/relay/)，它能自动操作批处理、缓存等等。但你并不需要一个复杂的客户端才能调用 GraphQL 服务器，在有了 `express-graphql` 的情况下，你可以向 GraphQL 服务器上的入口端点发送一个 HTTP P
“辟如”=>“譬如”

2017-08-07 17:24 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GraphQLClients.md
> +假设我们运行了 [Express GraphQL 服务器](/graphql-js/running-an-express-graphql-server/) 的案例代码，GraphQL 服务运行于 http://localhost:4000/graphql，我们想要发送 GraphQL 请求 `{ hello }`。我们在命令行中运行 `curl`，将下面代码粘贴到终端中去：
1. “案例代码”=>“示例代码”
2. “query”=>“查询”
3. “我们可以在命令行中使用 `curl` 来发送这一请求”

2017-08-07 17:24 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GraphQLClients.md
> +通过浏览器发送 GraphQL 也很简单。打开 http://localhost:4000，开启开发者终端，粘贴：
“console”=>“控制台”

2017-08-07 17:24 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GraphQLClients.md
> +你会在终端中见到返回的数据：
console +1

2017-08-07 17:24 UTC, ydfzgyj commented on site/graphql-js/Tutorial-GraphQLClients.md
> +假设你运行了 [传递参数](/graphql-js/passing-arguments/) 的案例服务器：
漏了"has a schema of"

2017-08-08 00:42 UTC, jonirrings commented on site/graphql-js/Tutorial-GraphQLClients.md
> +你会在终端中见到返回的数据：
好吧，一直 控制台，终端 当成一样的东西:joy:

2017-08-08 00:43 UTC, jonirrings commented on site/graphql-js/Tutorial-GraphQLClients.md
> +假设你运行了 [传递参数](/graphql-js/passing-arguments/) 的案例服务器：
已补充，有劳再次审校。……中文不好的锅

2017-08-08 03:30 UTC, ydfzgyj approved these changes

2017-08-08 03:41 UTC, linhe0x0 approved these changes

2017-08-09 04:17 UTC, merged