APIReference-Utilities.md
xitu/graphql.github.io pull request #70
Opened 2017-08-07 15:48 UTC by jonirrings

有劳审校

2017-08-09 10:53 UTC, ydfzgyj requested changes

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +      基于 GraphQL schema languag 构建一个 Schema 对象。
language 少了一个 e

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +      在 visitor 遍历 AST 时追踪类型和字段定义。
visitor 可以翻译的吧？

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +      判断一个 JavaScript 值是否是有效的 GraphQL 类型。
“值是有效的类型”有歧义，最后改成“……类型的值”如何

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +      判断一个 AST 中的字面量值是否是有效的 GraphQL 类型。
同上

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +      GraphQL 内省查询，包含足够的信息以重建类型系统。
“reproduce”翻译成“重现”比较好

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +GraphQL 内省查询，用于查询服务器的内省系统，得到足够的信息以重建服务器类型系统。
reproduce +1

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +假设客户端有运行内省查询的结果，创建并返回了一个 GraphQLSchema 实例，这个实例可以用于所有的 GraphQL.js工具，但不能用于执行查询，因为内省并不代表有“解析器”、“分析”或者“序列化”函数，或者其他服务器内部机制。
Graph.js 后加空格

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
>  *Introspection*
这里的小标题其他人都是翻译的，建议你也翻一下

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
>  ## Schema Representation
漏翻了

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +基于 GraphQL schema language 创建一个 GraphQLSchema 对象。schema 将会使用默认解析器。关于 GraphQL schema language 的更多细节，请查看 [schema language 文档](/learn/schema/) 或者  [schema language 速查表](https://wehavefaces.net/graphql-s
或者后边多了一个空格

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +TypeInfo 是一个工具类，在 GraphQL 文档 AST 的递归分析中的任何位置上，调用 `enter(node)` 和 `leave(node)` 的时候，可以追踪当前字段和类型定义。
given a GraphQL schema 漏了

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +给定一个 JavaScript 值和 GraphQL 类型，判断这个值是否能被这个类型接受。这个功能在验证运行时查询参数的时候特别有用。
runtime values 的 values 漏了

2017-08-09 10:53 UTC, ydfzgyj commented on site/graphql-js/APIReference-Utilities.md
> +注意，这个功能只验证字面量值，并假设变量值的是正确的类型。
“值的是”=>“指的是”？

2017-08-10 02:04 UTC, llp0574 commented on site/graphql-js/APIReference-Utilities.md
> +      在 visitor 遍历 AST 时追踪类型和字段定义。
我翻成了 **访问方法**，可以讨论统一一下

2017-08-10 03:18 UTC, jonirrings commented on site/graphql-js/APIReference-Utilities.md
> +      GraphQL 内省查询，包含足够的信息以重建类型系统。
可行

2017-08-10 03:19 UTC, jonirrings commented on site/graphql-js/APIReference-Utilities.md
> +      在 visitor 遍历 AST 时追踪类型和字段定义。
……这个不译比较好，是一个ast遍历用的类的实例。

2017-08-10 03:24 UTC, jonirrings commented on site/graphql-js/APIReference-Utilities.md
> +注意，这个功能只验证字面量值，并假设变量值的是正确的类型。
“的”多余

2017-08-10 03:29 UTC, jonirrings commented on site/graphql-js/APIReference-Utilities.md
>  *Introspection*
好的，除了我觉得保留的 和 api，都翻译了（就几个，哈哈）

2017-08-10 05:21 UTC, sqrthree commented on site/graphql-js/APIReference-Utilities.md
> +`graphql/utilities` 模块包含用于 GraphQL 语言和类型对象的常用计算。你可以从 `graphql/utilities` 模块或是根 `graphql` 模块引入。如下：
『根 `graphql` 模块』这里翻译成『根模块 `graphql`』或者『`graphql` 根模块』是不是更通顺一点捏

2017-08-10 06:03 UTC, jonirrings commented on site/graphql-js/APIReference-Utilities.md
> +`graphql/utilities` 模块包含用于 GraphQL 语言和类型对象的常用计算。你可以从 `graphql/utilities` 模块或是根 `graphql` 模块引入。如下：
后者吧~~

2017-08-10 06:31 UTC, sqrthree commented
@ydfzgyj 如果没什么疑问的话来 approve 一下吧。

2017-08-10 06:32 UTC, linhe0x0 approved these changes

2017-08-10 06:52 UTC, ydfzgyj approved these changes
Visitor 的问题，请 @jonirrings @llp0574 你们两位用到这个词的商议一下怎么统一吧

2017-08-10 07:11 UTC, jonirrings commented
@ydfzgyj 
@llp0574 我觉得这是PL实现相关的术语，最好不要译，你怎么看？

2017-08-10 08:04 UTC, llp0574 commented
@jonirrings 那就统一为不译吧
@sqrthree 我去修改一下重新提个pr

2017-08-10 08:09 UTC, jonirrings commented
嗯嗯。@llp0574 。有劳修改

2017-08-10 08:09 UTC, merged