Translate APIReference-Language.md
xitu/graphql.github.io pull request #73
Opened 2017-08-08 09:16 UTC by llp0574

close [#17](https://github.com/xitu/graphql.github.io/issues/17).

2017-08-08 09:17 UTC, llp0574 commented
@sqrthree 可以校对了。

2017-08-09 12:41 UTC, ydfzgyj requested changes

2017-08-09 12:41 UTC, ydfzgyj commented on site/graphql-js/APIReference-Language.md
> +### 词法分析
这里的 lex 是函数名，保留不翻译

2017-08-09 12:41 UTC, ydfzgyj commented on site/graphql-js/APIReference-Language.md
> +### 解析
保留不翻译+1

2017-08-09 12:41 UTC, ydfzgyj commented on site/graphql-js/APIReference-Language.md
> +当使用 `visit()` 编辑一个 AST 的时候，原始的 AST 不会被修改，`visit` 函数会生成一个经过修改的新版本 AST 返回。
“`visit` 函数会生成一个经过修改的新版本 AST 返回”=>“`visit` 函数会返回一个经过修改的新版本 AST”

2017-08-09 12:41 UTC, ydfzgyj commented on site/graphql-js/APIReference-Language.md
> +    //   false: 跳过访问该节点
这里是 no action

2017-08-09 12:41 UTC, ydfzgyj commented on site/graphql-js/APIReference-Language.md
>  </ul>
下边一行的 Printer 加粗

2017-08-09 12:51 UTC, linhe0x0 reviewed
LGTM

2017-08-09 12:51 UTC, sqrthree commented on site/graphql-js/APIReference-Language.md
> +### 词法分析
@llp0574 可参考 [需要保留英文的关键词](https://github.com/xitu/graphql.github.io/wiki/%E7%BF%BB%E8%AF%91%E6%9C%AF%E8%AF%AD%E8%A1%A8#%E9%9C%80%E8%A6%81%E4%BF%9D%E7%95%99%E8%8B%B1%E6%96%87%E7%9A%84%E5%85%B3%E9%94%AE%E8%AF%8D)

2017-08-09 12:51 UTC, sqrthree commented on site/graphql-js/APIReference-Language.md
> +### 解析
@ydfzgyj 根据 wiki 中 [不需要保留英文的关键词](https://github.com/xitu/graphql.github.io/wiki/%E7%BF%BB%E8%AF%91%E6%9C%AF%E8%AF%AD%E8%A1%A8#%E4%B8%8D%E9%9C%80%E8%A6%81%E4%BF%9D%E7%95%99%E8%8B%B1%E6%96%87%E7%9A%84%E5%85%B3%E9%94%AE%E8%AF%8D) 中『parser』不需要保留英文，直接翻译。那么『parse』是不是也应该采取同样的策略呢？

2017-08-09 14:41 UTC, ydfzgyj commented on site/graphql-js/APIReference-Language.md
> +### 解析
并非是因为需要保留英文而不翻译，而是因为这里的标题是作为 API 文档中的函数名出现，所以不翻译 @sqrthree

2017-08-09 15:34 UTC, sqrthree commented on site/graphql-js/APIReference-Language.md
> +### 解析
好哒

2017-08-10 01:58 UTC, llp0574 commented
感谢 @ydfzgyj 建议，已修改。

2017-08-10 02:13 UTC, ydfzgyj approved these changes

2017-08-10 02:43 UTC, linhe0x0 approved these changes

2017-08-10 02:44 UTC, merged