Tutorial-ObjectTypes.md
xitu/graphql.github.io pull request #74
Opened 2017-08-08 15:45 UTC by JustClear

有劳校对

2017-08-09 17:58 UTC, ydfzgyj requested changes
问题稍稍有点多，请继续加油！

2017-08-09 17:58 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +在 GraphQL schema 语言中，定义一个新的对象类型就和我们在示例中定义的 `Query` 类型一样。每个对象可以有返回指定类型的的字段，或者带有参数的方法。例如，在 [参数传递](/graphql-js/passing-arguments/) 中，我们有一个掷骰子的方法：
1. “GraphQL schema language”全部保留不翻译
2. 返回指定类型“的的”字段，多了一个的
3. “以及”带有参数的方法，不是“或者”
4. 在参数传递“一节”中

2017-08-09 17:58 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +取而代之的是一个值为 `RandomDie` 类型的根级别解析器，我们可以用 ES6 的 class 语法来替代，这样的话这些解析器就是这个类的实例方法了。下面的代码展示了如何使用 ES6 的 class 语法来实现上面的 `RandomDie` 对象类型：
前半句的意思是使用 ES6 class 代替 resolver，现在的翻译有些问题

2017-08-09 17:58 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +最后把这些代码都整到一起，这里是一些运行了用了该 GraphQL API 的示例代码：
1. 兄弟是东北人吗，“整到一起”……😂 换一个书面一些的用词吧
2. 后半句 “这里是一些使用该 GraphQL API 运行服务器的示例代码：”

2017-08-09 17:58 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +当你对一个 API 发出一个 GraphQL 查询时它会返回一个对象类型，你可以通过嵌套 GraphQL 字段名来调用对象上的多个方法。例如，如果你想在调用一次 `rollOnce` 方法的同时也调用 `roll` 方法来掷 3 次骰子的话，你可以这么做：
1. 第一句 “当你对一个返回对象类型的 API 发出 GraphQL 查询时”
2. 第二句漏到了 “at once”
3. 第三句 “如果你想在调用 `rollOnce` 方法掷一次骰子的同时……”

2017-08-09 17:58 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +如果你用 `node server.js` 命令来运行这些代码并且访问 http://localhost:4000/graphql 的话，你可以用 GraphQL 试一下这些 API。
你可以用 “ GraphiQL”，不是“ GraphQL”

2017-08-09 17:58 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +这种定义对象类型的方式通常会比传统的 REST 风格的 API 会带来更多的好处。取而代之的是只需要请求一次 API 就可以获得一个对象的相关基本信息，或者可以通过多个附带的 API 请求来获取更多关于该对象的信息，当然你也可以通过一次请求来获取该对象的所有信息。这样不仅节省了带宽、让你的应用跑得更快，同时也简化了你客户端应用的逻辑。
第二句，还是 “Instead of”的问题，这个词所引导的句子都是指“被取而代之”，所以这句的意思是“你可以只用一次请求，**而不是** 一次 API 只能获得一个对象，然后还得再加一堆 API 获取其他对象”

2017-08-09 17:58 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +到目前为止，我们所看到的每个 API 都是为返回数据而设计的。为了修改存储的数据或处理复杂的输入，它有助于学习 [mutations 和 input types](/graphql-js/mutations-and-input-types/)。
1. learn about 是在链接里边的
2. “为了……，它有助于……”我觉得不通，虽然原文也感觉不通，我觉得不如干脆直接无视原文，改成“为了……，需要继续学习……”

2017-08-10 05:23 UTC, linhe0x0 reviewed
代码注释也需要翻译哈。

2017-08-10 05:24 UTC, linhe0x0 requested changes
代码注释也需要翻译哈。

2017-08-11 16:17 UTC, JustClear commented on site/graphql-js/Tutorial-ObjectTypes.md
> +最后把这些代码都整到一起，这里是一些运行了用了该 GraphQL API 的示例代码：
是整理整理😂

2017-08-14 05:17 UTC, ydfzgyj requested changes

2017-08-14 05:17 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +// root 规定了顶层的 API 端点
endpoint 统一译为 “入口端点”

2017-08-14 05:17 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +// 该类继承 RandomDie GraphQL 类型
英文原文的注释需要删掉

2017-08-14 05:17 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +这种定义对象类型的方式通常会比传统的 REST 风格的 API 会带来更多的好处。你可以只用一次请求，而不是一次 API 只能获得一个对象，然后还得再加一堆 API 获取其他对象，当然你也可以通过一次请求来获取该对象的所有信息。这样不仅节省了带宽、让你的应用跑得更快，同时也简化了你客户端应用的逻辑。
……我只是写了大概意思，不能直接 Copy 过来啊，请重新译一下这段

2017-08-14 05:17 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +当你对一个返回对象类型的 API 发出 GraphQL 查询时，你可以通过嵌套 GraphQL 字段名来调用对象上的多个方法。例如，如果你想在调用 `rollOnce` 方法掷 1 次骰子的同时也调用 `roll` 方法来掷 3 次骰子的话，你可以这么做：
还是漏了 at once 的翻译

2017-08-14 05:17 UTC, ydfzgyj commented on site/graphql-js/Tutorial-ObjectTypes.md
> +对于跟级别解析器 `RandomDie` 类型来说，我们可以用 ES6 的 class 语法来替代，这样的话这些解析器就是这个类的实例方法了。下面的代码展示了如何使用 ES6 的 class 语法来实现上面的 `RandomDie` 对象类型：
“对于跟级别解析器 `RandomDie` 类型来说”=>“对于 `RandomDie` 类型的根级别解析器来说”

2017-08-14 06:19 UTC, JustClear commented on site/graphql-js/Tutorial-ObjectTypes.md
> +// 该类继承 RandomDie GraphQL 类型
Sorry, 漏了删😂

2017-08-14 06:19 UTC, JustClear commented on site/graphql-js/Tutorial-ObjectTypes.md
> +对于跟级别解析器 `RandomDie` 类型来说，我们可以用 ES6 的 class 语法来替代，这样的话这些解析器就是这个类的实例方法了。下面的代码展示了如何使用 ES6 的 class 语法来实现上面的 `RandomDie` 对象类型：
👌

2017-08-14 15:56 UTC, JustClear commented on site/graphql-js/Tutorial-ObjectTypes.md
> +这种定义对象类型的方式通常会比传统的 REST 风格的 API 会带来更多的好处。取而代之的是只需要请求一次 API 就可以获得一个对象的相关基本信息，或者可以通过多个附带的 API 请求来获取更多关于该对象的信息，当然你也可以通过一次请求来获取该对象的所有信息。这样不仅节省了带宽、让你的应用跑得更快，同时也简化了你客户端应用的逻辑。
还是想请教一下这句话怎么翻译比较好呢

2017-08-14 17:20 UTC, ydfzgyj approved these changes

2017-08-15 03:42 UTC, linhe0x0 approved these changes

2017-08-15 03:43 UTC, merged